Repository habitat-sh/core-plans, pull requests merged in 2018-11, with the labels that each got.

#1956 [curl] Update curl to 7.62.0
  curl/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1960 [dotnet-core] Updated version to 2.1.5
  dotnet-core/plan.ps1
  dotnet-core/plan.sh
Labels: A-core-plans, C-minor-version-up

#1962 [memcached] Update memcached to 1.5.12
  memcached/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1957 [img] Update img to 0.5.2, add some basic image build tests
  img/plan.sh
  img/tests/test.bats
  img/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1970 [logstash] Update logstash to 6.4.3, add tests
  logstash/plan.sh
  logstash/tests/test.bats
  logstash/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1937 [artifactory] updating artifactory to 6.5.2
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1985 [scaffolding-chef] add ability for other software to bind off chef_client_ident
  scaffolding-chef/lib/scaffolding.sh
  scaffolding-chef/plan.sh
Labels: A-scaffolding, C-feature, C-minor-version-up, V-core-plans

#1971 [nginx] Update Nginx to 1.15.6 for Linux and Windows
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1968 [filebeat] Update filebeat to 6.4.3, add tests
  filebeat/plan.sh
  filebeat/tests/test.bats
  filebeat/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1967 [dgraph] Update dgraph to 1.0.10, update readme
  dgraph/README.md
  dgraph/plan.sh
  dgraph/tests/test.bats
  dgraph/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1991 [libuv] Update libuv to 1.24.0
  libuv/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1989 [caddy] Update caddy to 0.11.1
  caddy/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1990 [jruby] Update jruby to 9.2.4.0, standardize some variable usage
  jruby/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1972 [vault] Change backend to storage in configuration
  vault/config/settings.hcl
Labels: A-core-plans, C-bug, V-core-plans

#1992 [vault] Update Vault to 0.11.5
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1988 [consul] Update consul to 1.3.1
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1995 [Artifactory-Pro] Updating 6.5.3
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#1969 [elasticsearch5] Update elasticsearch5 to 5.6.13, fix missing deps, added tests
  elasticsearch/plan.sh
  elasticsearch5/README.md
  elasticsearch5/plan.sh
  elasticsearch5/tests/test.bats
  elasticsearch5/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1997 [go] bump 1.11.1 -> 1.11.2
  go/plan.sh
Labels: C-minor-version-up

#2000 [chrony] Added core/chrony
  .bldr.toml
  chrony/README.md
  chrony/plan.sh
Labels: C-new-plan

#1958 [curl-static-musl] Update curl-static-musl to 7.62.0
  curl-static-musl/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2005 [dotnet-asp-core] Updating to 2.1.6
  dotnet-asp-core/plan.ps1
  dotnet-asp-core/plan.sh
Labels: A-core-plans, C-minor-version-up

#1795 Initial commit of plan variants
  glibc/x86_64-linux-kernel2/0005-fix-binutils-2-29-build.patch
  glibc/x86_64-linux-kernel2/dont-use-system-ld-so.patch
  glibc/x86_64-linux-kernel2/gcc-implicit-boolean.patch
  glibc/x86_64-linux-kernel2/glibc-2.23-upstream_fixes-1.patch
  glibc/x86_64-linux-kernel2/nss-nisplus-gcc7.patch
  glibc/x86_64-linux-kernel2/plan.sh
  glibc/x86_64-linux-kernel2/remove-sun-rpm-bug.patch
  glibc/x86_64-linux-kernel2/rpcgen-path.patch
  glibc/x86_64-linux-kernel2/testsuite-fix.patch
  libcap/x86_64-linux-kernel2/README.md
  libcap/x86_64-linux-kernel2/libcap-old-kernel-headers.patch
  libcap/x86_64-linux-kernel2/plan.sh
  libsodium/plan.sh
  linux-headers/x86_64-linux-kernel2/plan.sh
Labels: A-core-plans, C-feature

#2004 [direnv] Update direnv to 2.18.2
  direnv/plan.sh
Labels: C-minor-version-up

#1996 [node/node11] Update node to 11.2.0
  node/plan.sh
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans
