Repository habitat-sh/core-plans, pull requests merged in 2018-04, with the labels that each got.

#1300 [prometheus-cpp] add new plan
  .bldr.toml
  prometheus-cpp/README.md
  prometheus-cpp/plan.sh
Labels: C-new-plan

#1308 [ninja] bump to 1.8.2 and add do_check
  ninja/README.md
  ninja/plan.sh
Labels: C-minor-version-up

#1301 [httpd] Fix: apxs requires a Perl interpreter
  httpd/plan.sh
Labels: C-bug

#1313 [glib] Fixes python requirement at runtime
  glib/plan.sh
Labels: C-bug

#1315 [jre9] Fixes package and bumps to 9.0.4
  jre9/plan.sh
Labels: C-bug, C-minor-version-up

#1319 [wal-e] Update to 1.1.0
  wal-e/plan.sh
Labels: A-core-plans, C-minor-version-up

#1102 [bind] Adds bind package
  .bldr.toml
  bind/README.md
  bind/plan.sh
Labels: C-new-plan

#1312 Removes incorrect wal_e tunables from postgresql94 config
  postgresql94/config/functions.sh
  postgresql94/config/pg_hba.conf
  postgresql94/config/pg_ident.conf
  postgresql94/config/postgresql.conf
  postgresql94/config/pwfile
  postgresql94/config/recovery.conf
  postgresql94/default.toml
  postgresql94/hooks/health_check
  postgresql94/hooks/init
  postgresql94/hooks/reconfigure
  postgresql94/hooks/run
  postgresql94/hooks/suitability
  postgresql94/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#1325 [benchmark] add new plan
  .bldr.toml
  benchmark/README.md
  benchmark/plan.sh
Labels: A-core-plans, C-new-plan

#1003 [gtk] Adds gtk package (gtk3)
  .bldr.toml
  gtk/README.md
  gtk/plan.sh
Labels: C-new-plan

#1322 adding a dsc-core plan
  CODEOWNERS
  dsc-core/DSCCore.psd1
  dsc-core/DSCCore.psm1
  dsc-core/README.md
  dsc-core/plan.ps1
Labels: C-new-plan

#1323 adds a sqlserver plan
  CODEOWNERS
  sqlserver/README.md
  sqlserver/config/config.ini
  sqlserver/config/firewall.ps1
  sqlserver/config/sql_login.sql
  sqlserver/config/windows_login.sql
  sqlserver/default.toml
  sqlserver/hooks/init
  sqlserver/hooks/post-run
  sqlserver/hooks/post-stop
  sqlserver/hooks/run
  sqlserver/plan.ps1
Labels: C-new-plan

#1324 adds a plan got sqlserver-ha
  CODEOWNERS
  sqlserver-ha-ag/README.md
  sqlserver-ha-ag/config/cluster.ps1
  sqlserver-ha-ag/config/feature.ps1
  sqlserver-ha-ag/config/firewall.ps1
  sqlserver-ha-ag/config/group.ps1
  sqlserver-ha-ag/default.toml
  sqlserver-ha-ag/hooks/init
  sqlserver-ha-ag/hooks/run
  sqlserver-ha-ag/plan.ps1
Labels: C-new-plan

#1239 [protobuf-rust] Update rust protobuf version
  protobuf-rust/plan.sh
Labels: C-minor-version-up

#1329 [zeromq] bump zeromq to 4.2.5
  zeromq/README.md
  zeromq/plan.sh
Labels: C-minor-version-up

#1334 [protobuf-rust] Removes useless dependencies
  protobuf-rust/plan.sh
Labels: C-chore

#1332 [compositeproto] Creates package
  .bldr.toml
  compositeproto/README.md
  compositeproto/plan.sh
Labels: C-new-plan

#1342 Add missing forums link href
  README.md
Labels: C-chore

#1335 [libtasn1] Creates package
  .bldr.toml
  libtasn1/README.md
  libtasn1/plan.sh
Labels: C-new-plan

#1336 [nettle] Creates package
  .bldr.toml
  nettle/README.md
  nettle/plan.sh
Labels: C-new-plan

#1337 [p11-kit] Creates package
  .bldr.toml
  p11-kit/README.md
  p11-kit/plan.sh
Labels: C-new-plan

#1333 [libxcomposite] Creates package
  .bldr.toml
  libxcomposite/README.md
  libxcomposite/plan.sh
Labels: C-new-plan

#1340 [scrnsaverproto] Creates package
  .bldr.toml
  scrnsaverproto/README.md
  scrnsaverproto/plan.sh
Labels: C-new-plan

#1341 [libxscrnsaver] Creates package
  .bldr.toml
  libxscrnsaver/README.md
  libxscrnsaver/plan.sh
Labels: C-new-plan

#1338 [gnutls] Creates package
  .bldr.toml
  gnutls/README.md
  gnutls/plan.sh
Labels: C-new-plan

#1343 [alsa-lib] Creates package
  .bldr.toml
  alsa-lib/README.md
  alsa-lib/plan.sh
Labels: C-new-plan

#1138 [scaffolding-go] separating build and run deps
  scaffolding-go/plan.sh
Labels: S-needs-testing

#1280 adds RFC for defining how we track versions of software that are pack…
  _RFCs/0003-tracking-package-versions.md
Labels: C-RFC, S-IN-FCP

#1296 Adds RFC to change Java8 package versions
  _RFCs/0005-rfc-java-semantic-versioning.md
Labels: C-RFC, S-IN-FCP

#1281 adds rfc around testing pull requests
  _RFCs/0004-testing-pull-requests.md
Labels: C-RFC, S-IN-FCP

#1370 [jdk9] Updates to 9.0.4 (fixes build)
  jdk9/plan.sh
Labels: C-bug, C-minor-version-up

#1374 Whitespace-only commit
  7zip/plan.ps1
  crate/default.toml
  drupal/config/nginx.conf
  drupal/default.toml
  mariadb/config/init.sql
  mariadb/config/my.cnf
  mariadb/default.toml
  mariadb/hooks/init
  mariadb/hooks/run
  varnish/hooks/run
  varnish/tests/scripts/varnish-ready
  visual-build-tools-2017/plan.ps1
  wordpress/README.MD
Labels: C-chore

#1373 [libxshmfence] Fixes build for base packages refresh
  libxshmfence/plan.sh
Labels: C-chore

#1371 [elfutils] Update to 0.170
  elfutils/plan.sh
Labels: C-minor-version-up

#1367 [openssh] use more resilient mirror to get sources
  openssh/plan.sh
Labels: C-bug

#1368 [go14] Fixes build with latest base package
  go14/plan.sh
Labels: C-chore

#1390 [curl-static-musl] Fixes package
  curl-static-musl/plan.sh
Labels: C-bug

#1386 [clingo] Update to 5.2.2
  clingo/plan.sh
Labels: C-minor-version-up

#1388 [iproute2] Update to 4.16.0
  iproute2/plan.sh
Labels: C-minor-version-up

#1387 [libuv] Fixes package
  libuv/plan.sh
Labels: C-bug

#1385 [e2fsprogs] Updates to 1.44.1
  e2fsprogs/README.md
  e2fsprogs/plan.sh
Labels: C-minor-version-up

#1089 [bdwgc] Updates bdwgc to 7.6.0
  bdwgc/plan.sh
Labels: C-minor-version-up

#1403 [mssql] Update to 14.0.3025.34-1
  mssql/plan.sh
Labels: C-minor-version-up

#1393 [jruby] Fixes package build
  jruby/plan.sh
Labels: C-bug

#1407 [zookeeper] Updates to 3.4.11
  zookeeper/plan.sh
Labels: C-minor-version-up

#1406 [storm] Update to 1.1.2
  storm/plan.sh
Labels: C-minor-version-up

#1401 [libpcap] Adds pconfig_dirs
  libpcap/plan.sh
Labels: C-chore

#1405 [sumologic] Updates to 19.209-37
  sumologic/plan.sh
Labels: C-minor-version-up

#1395 [fish] Fixes pkg_source URL
  fish/plan.sh
Labels: C-bug

#1413 [jdk8] Updates to 8.172.0
  jdk8/plan.sh
Labels: C-minor-version-up, S-needs-testing

#1412 [jre8] Update to 8.172.0
  jre8/plan.sh
Labels: C-minor-version-up, S-needs-testing

#1404 [kafka] Updates to 0.10.2.1
  kafka/plan.sh
Labels: C-minor-version-up, S-needs-testing

#1417 [leiningen] Makes use of latest jdk8 package
  leiningen/plan.sh
Labels: C-chore

#1327 Add RFC around pull request approvals
  _RFCs/0006-rfc-gh-approval-reset.md
Labels: C-RFC, S-IN-FCP

#1453 [CONTRIBUTING] Adds requirement on dependencies
  CONTRIBUTING.md
Labels: C-chore

#1458 [postgresql] Update to 9.6.8
  postgresql/plan.sh
Labels: C-minor-version-up

#1449 [flatbuffers] Update to 1.9.0
  flatbuffers/plan.sh
Labels: C-minor-version-up

#1448 [docker-compose] Update to 1.21.0
  docker-compose/plan.sh
Labels: C-minor-version-up

#1454 [prometheus-cpp] Update to 0.4.1
  prometheus-cpp/plan.sh
Labels: C-minor-version-up

#1451 [lsyncd] Update to 2.2.1
  lsyncd/plan.sh
Labels: C-minor-version-up

#1447 [lynx] Allows build in base refresh
  lynx/ncurses.patch
  lynx/plan.sh
Labels: C-bug

#1445 [lzop] Updates to 1.04
  lzop/plan.sh
Labels: C-minor-version-up

#1446 [qemu] Update to 2.11.1
  qemu/glibc-2.27.patch
  qemu/plan.sh
Labels: C-minor-version-up

#1444 [nss] Upgrades to 3.35 (m)
  nss/plan.sh
Labels: C-minor-version-up

#1443 [bash-completion] Update to 2.7
  bash-completion/plan.sh
Labels: C-minor-version-up

#1450 [cockroach] Remove pin on go version
  cockroach/plan.sh
Labels: C-chore

#1456 [scaffolding-go] Changes default GOPATH location
  scaffolding-go/lib/scaffolding.sh
Labels: C-chore

#1461 [R]: bump to 3.5.0 and README
  R/README.md
  R/plan.sh
Labels: C-minor-version-up

#1463 [Vault] Updating Vault and adding README
  vault/README.md
  vault/plan.sh
Labels: C-minor-version-up

#1100 [grafana] Bump grafana version to 4.6.3
  grafana/README.md
  grafana/config/grafana.ini
  grafana/config/ldap.toml
  grafana/hooks/run
  grafana/plan.sh
Labels: C-minor-version-up, S-needs-testing

#1372 [llvm] Speeds up build using -j
  llvm/plan.sh
Labels: C-chore

#1487 [clang] speed up build
  clang-tools-extra/plan.sh
  clang/plan.sh
Labels: C-chore
