Repository habitat-sh/core-plans, pull requests merged in 2018-08, with the labels that each got.

#1740 [kubectl] Update Kubectl plan
  kubectl/plan.sh
Labels: C-minor-version-up

#1756 [go] update Go plan
  go/plan.sh
Labels: C-minor-version-up

#1742 [sbt] add new plan using version 1.1.6
  .bldr.toml
  sbt/README.md
  sbt/plan.sh
Labels: C-new-plan, S-needs-discussion

#1755 [protobuf-rust] Update protobuf-rust to 1.7.4
  protobuf-rust/plan.sh
Labels: C-minor-version-up

#1754 [protobuf-cpp] Update protobuf-cpp to 3.6.1
  protobuf-cpp/plan.sh
Labels: C-minor-version-up

#1753 [protobuf] Update protobuf to 3.6.1
  protobuf/plan.sh
Labels: C-minor-version-up

#1759 [node/node10] Update NodeJS to 10.8.0
  node/plan.sh
  node10/plan.sh
Labels: C-minor-version-up

#1748 [redis3] Update redis to 3.2.12
  redis3/plan.sh
  redis4/plan.sh
Labels: C-minor-version-up

#1763 [git] Update git to 2.18.0
  git/plan.ps1
  git/plan.sh
Labels: C-minor-version-up

#1760 [rust] Update to Rust 1.28.0.
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-core-plans, V-infra

#1738 [leproxy] Add new plan for leproxy
  .bldr.toml
  leproxy/README.md
  leproxy/plan.sh
Labels: C-new-plan, S-needs-discussion

#1769 [mage] New plan: mage
  .bldr.toml
  mage/README.md
  mage/plan.sh
Labels: C-new-plan

#1773 [zookeeper] Update zookeeper to 3.4.13
  zookeeper/plan.sh
Labels: C-minor-version-up

#1772 [zsh] Update to zsh 5.5.1, fix tests
  zsh/plan.sh
Labels: C-minor-version-up

#1778 Openresty update to 1.13.6.1
  openresty/plan.sh
Labels: C-minor-version-up

#1777 [lessmsi] Update lessmsi to 1.6.1
  lessmsi/plan.ps1
Labels: C-minor-version-up

#1779 [aspnet-mvc1] adding core plan for ASP.NET MVC v1
  aspnet-mvc1/README.md
  aspnet-mvc1/plan.ps1
Labels: C-new-plan

#1782 [memcached] Update memcached to 1.5.10
  memcached/plan.sh
Labels: C-minor-version-up

#1764 [sensu] security updates
  sensu/Gemfile
  sensu/config/config.json
  sensu/config/server.json
  sensu/default.toml
  sensu/hooks/run
  sensu/plan.sh
Labels: C-major-version-up

#1791 PHP update to 7.2.8
  php/plan.sh
Labels: C-minor-version-up

#1789 [strace] Update strace to 4.24, add testing
  strace/plan.sh
  strace/test.bats
  strace/test.sh
Labels: C-minor-version-up

#1794 [terraform] Update terraform to 0.11.8, add testing
  terraform/plan.sh
  terraform/test.bats
  terraform/test.sh
Labels: C-minor-version-up

#1781 [docutils] Move core/python2 to pkg_deps from pkg_build_deps. Fixes #1780
  docutils/README.md
  docutils/plan.sh
Labels: C-bug

#1785 [docutils] Bump version of package to current
  docutils/plan.sh
Labels: C-minor-version-up

#1801 [minio] Update minio to 2018-08-18T03-49-57Z
  minio/plan.sh
Labels: C-minor-version-up

#1810 [jenkins] Update to 2.121.3 - Security updates
  jenkins/plan.sh
Labels: C-minor-version-up

#1813 [Sumologic] Updating to 9.227-12/ Bug Fixes
  sumologic/README.md
  sumologic/config/wrapper-license.conf
  sumologic/hooks/run
  sumologic/plan.sh
  sumologic/test.sh
Labels: C-minor-version-up
