Repository habitat-sh/core-plans, pull requests merged in 2018-05, with the labels that each got.

#1497 [zookeeper] Update to 3.4.12
  zookeeper/plan.sh
Labels: C-minor-version-up

#1498 [pax-utils] Update to 1.2.3
  pax-utils/plan.sh
Labels: C-minor-version-up

#1508 [mono5] Update to 5.10.1.47
  mono5/plan.sh
Labels: C-minor-version-up

#1530 [consul] Upgrade to 1.1.0
  consul/plan.sh
Labels: C-minor-version-up

#1547 Another bump of the Tor version, new stable 0.3.3.6
  tor/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1540 [RethinkDB] Version up to 2.3.6
  rethinkdb/README.md
  rethinkdb/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1545 [concourse] Updated concourse and fly for 3.13.0
  concourse-fly/plan.sh
  concourse/plan.sh
Labels: C-minor-version-up, V-core-plans
