Repository habitat-sh/core-plans, pull requests merged in 2018-07, with the labels that each got.

#1631 [scaffolding-node] Update scaffolding-node to handle double-digit version constraints.
  scaffolding-node/lib/scaffolding.sh
  scaffolding-node/plan.sh
Labels: A-scaffolding

#1615 [tar] Skip a test that inconsistently fails.
  tar/plan.sh
  tar/skip-test.patch
Labels: A-core-plans, C-bug, E-less-easy, I-linux, L-shell, V-core-plans

#1638 [dotnet-462-dev-pack] Add new plan
  dotnet-462-dev-pack/README.md
  dotnet-462-dev-pack/plan.ps1
Labels: C-new-plan

#1644 [mc] Update to 4.8.21, prefer xz tarball
  mc/plan.sh
Labels: C-minor-version-up

#1641 [tmux] upgrade to 2.7
  tmux/plan.sh
Labels: C-minor-version-up

#1592 Bump jruby version to 9.2.0.0
  jruby/plan.sh
Labels: S-needs-discussion

#1543 [sqlserver] add nuget provider download
  sqlserver/hooks/init
Labels: S-needs-testing

#1655 [logstash] update to 6.3.1
  logstash/plan.sh
Labels: C-minor-version-up

#1654 [filebeat] update to 6.3.1
  filebeat/README.md
  filebeat/plan.sh
Labels: C-minor-version-up

#1664 [postfix] Version bump to 3.3.1, fix path problem
  postfix/plan.sh
Labels: C-minor-version-up

#1663 [jenkins] Upgrade to 2.121.1
  jenkins/README.md
  jenkins/plan.sh
Labels: C-minor-version-up

#1662 [memcached] Upgrade to 1.5.9, add readme
  memcached/README.md
  memcached/plan.sh
Labels: C-minor-version-up

#1667 [mongodb] Fix mongodb linking
  mongodb/plan.sh
Labels: C-bug, S-needs-testing

#616 Added GHC plan for core
  .bldr.toml
  ghc/README.md
  ghc/plan.sh
  ghc710-bootstrap/README.md
  ghc710-bootstrap/plan.sh
  ghc710/README.md
  ghc710/plan.sh
  ghc80/README.md
  ghc80/plan.sh
  ghc82-bootstrap/README.md
  ghc82-bootstrap/plan.sh
  ghc82/README.md
  ghc82/plan.sh
  ghc84/README.md
  ghc84/plan.sh
  ncurses5/README.md
  ncurses5/plan.sh
Labels: C-new-plan, S-needs-discussion

#1670 [hugo] Version up to 0.43
  hugo/plan.sh
Labels: C-minor-version-up

#1671 [gocd-server] New package - GoCD Server
  .bldr.toml
  CODEOWNERS
  gocd-server/README.md
  gocd-server/default.toml
  gocd-server/hooks/run
  gocd-server/plan.sh
Labels: C-new-plan

#1681 [consul] Update to 1.2.1, Allow legacy UI
  consul/default.toml
  consul/hooks/run
  consul/plan.sh
Labels: C-minor-version-up

#1680 [mongodb] Remove deprecated settings from mongod.conf
  mongodb/config/mongod.conf
  mongodb/default.toml
Labels: C-bug, S-needs-testing

#1686 [hugo] Update hugo to 0.44
  hugo/plan.sh
Labels: C-minor-version-up

#1687 [gnatsd] added config files for gnatsd
  gnatsd/config/default.conf
  gnatsd/default.toml
  gnatsd/plan.sh
Labels: A-core-plans, C-feature

#1702 [packer] Update packer to 1.2.5
  packer/plan.sh
Labels: C-minor-version-up

#1703 [libpng] Update libpng to 1.6.35
  libpng/plan.sh
Labels: C-minor-version-up

#1710 [node] Update core/node to 8.11.3 for consistency with core/node8
  node/plan.sh
Labels: C-minor-version-up

#1709 [jenkins] Update to 2.121.2 (security updates)
  jenkins/plan.sh
Labels: C-minor-version-up

#1708 [rust] Update to Rust 1.27.1.
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-bldr, V-core-plans, V-devx, V-sup

#1711 [node] Update to version 10.7.0
  node/plan.sh
Labels: C-major-version-up

#1707 [php] Update to PHP 7.2.7
  php/plan.sh
Labels: C-minor-version-up

#1725 [strace] Update strace to 4.23
  strace/plan.sh
Labels: C-minor-version-up

#1726 [rabbitmq] Update RabbitMQ to 3.7.7
  rabbitmq/plan.sh
Labels: C-minor-version-up

#1723 [etcd] Update etcd to 3.3.9
  etcd/plan.sh
Labels: C-minor-version-up

#1727 [rabbitmqadmin] Update RabbitMQ Admin to 3.7.7
  rabbitmqadmin/plan.sh
Labels: C-minor-version-up

#1730 [hugo] Update hugo to 0.45.1
  hugo/plan.sh
Labels: C-minor-version-up

#1733 Bump versions for gnatsd and nats-streaming-server
  gnatsd/plan.sh
  nats-streaming-server/plan.sh
Labels: C-minor-version-up

#1734 [dep] Update golang dep to 0.5.0
  dep/plan.sh
Labels: C-minor-version-up

#1741 [consul] Update consul to 1.2.2, and add testing
  consul/plan.sh
  consul/test.sh
Labels: C-minor-version-up
