Repository habitat-sh/core-plans, pull requests merged in 2018-06, with the labels that each got.

#1544 Add a Chef Scaffolding
  scaffolding-chef/README.md
  scaffolding-chef/lib/scaffolding.sh
  scaffolding-chef/plan.sh
Labels: A-scaffolding, C-new-plan, V-core-plans

#1575 [rust] Update to Rust 1.26.2.
  rust/plan.ps1
  rust/plan.sh
Labels: C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-core-plans, V-infra

#1574 [popt] Update source_url & fix variable name
  popt/plan.sh
Labels: A-core-plans, C-bug, E-easy, I-linux, L-shell, V-core-plans

#1579 [node] Bump to 8.11.2
  node/plan.ps1
  node/plan.sh
Labels: C-minor-version-up

#1578 [hugo] Update hugo to 0.41
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1582 [Vault] Updated plan to Vault 0.10.2
  vault/plan.sh
Labels: C-minor-version-up

#1581 [direnv] update to 2.16.0
  direnv/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1577 [rust] Patch additional ELF binaries in Rust package.
  rust/plan.sh
Labels: A-core-plans, C-bug, E-easy, I-linux, L-shell, V-core-plans

#1595 upgrade version of python
  python/plan.sh
Labels: C-minor-version-up
