Repository habitat-sh/core-plans, pull requests merged in 2018-02, with the labels that each got.

#1203 [rust] Update to Rust 1.24.0.
  rust/plan.ps1
  rust/plan.sh
Labels: C-release

#1170 Bump docker-ce version to 17.09.1
  docker/plan.sh
Labels: Minor Version Bump

#1156 [memcached] Update memcached to 1.5.4
  memcached/plan.sh
Labels: Minor Version Bump

#1147 [cmake] lets get cmake up-to-date
  cmake/plan.sh
Labels: Minor Version Bump

#1062 [python2] Updated the Python 2 version to the latest 2.7.14
  python2/plan.sh
Labels: Minor Version Bump

#1092 [nginx] upgrade to 1.12.2
  nginx/plan.sh
Labels: Minor Version Bump, Need owner approve
