Repository habitat-sh/core-plans, pull requests merged in 2018-12, with the labels that each got.

#2018 [dotnet-core] Updating dotnet-core to 2.1.6
  dotnet-core/plan.ps1
  dotnet-core/plan.sh
Labels: A-core-plans, C-minor-version-up

#2015 [artifactory-pro] Updating version to 6.5.9
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#2014 [consul] Updating version to 1.4.0
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up

#2013 [etcd] Update to 3.3.10 w/tests
  etcd/plan.sh
  etcd/tests/test.bats
  etcd/tests/test.sh
Labels: A-core-plans, C-minor-version-up

#2019 [libpng] Update libpng to 1.6.36
  libpng/plan.sh
Labels: C-minor-version-up

#2022 [sbt] Update sbt to 1.2.7, minor cleanup
  sbt/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2016 [dotnet-core-sdk] Updating Linux and Windows plans to 2.1.500
  dotnet-core-sdk/plan.ps1
  dotnet-core-sdk/plan.sh
Labels: A-core-plans, C-minor-version-up

#2001 [goaccess] add plan
  .bldr.toml
  goaccess/README.md
  goaccess/plan.sh
  goaccess/tests/test.bats
  goaccess/tests/test.sh
Labels: C-new-plan

#2026 [vault] Upgrade vault to 1.0.0, add tests, change storage
  vault/README.md
  vault/config/settings.hcl
  vault/default.toml
  vault/hooks/init
  vault/plan.sh
  vault/tests/test.bats
  vault/tests/test.sh
Labels: A-core-plans, C-major-version-up, V-core-plans

#2029 [php] Update PHP to 7.3.0
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2027 [hugo] Update Hugo to 0.52
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2042 [openssl] Update openssl from 1.0.2n to 1.0.2q
  openssl/plan.ps1
  openssl/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2063 [filebeat] Update filebeat to 6.5.3
  filebeat/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2043 [opa] bump 0.10.1 -> 0.10.2
  opa/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2064 [node8] Update Node8 to 8.14.0
  node8/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2078 [terraform] Updating to 0.11.11
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up

#2058 [vim] Update vim from 8.1.0450 -> 8.1.0577
  vim/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2038 [nettle] Upgrade nettle to 3.4.1
  nettle/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2039 [gnutls] Update gnutls to 3.6.5
  gnutls/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2060 [tzdata] Update tzdata 2018e -> 2018g
  tzdata/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2066 [dotnet-core] Updated Windows/Linux Plans to 2.2.0
  dotnet-core/plan.ps1
  dotnet-core/plan.sh
Labels: A-core-plans, C-minor-version-up

#2067 [dotnet-core-sdk] Updating to version 2.2.101
  dotnet-core-sdk/plan.ps1
  dotnet-core-sdk/plan.sh
Labels: A-core-plans, C-minor-version-up

#2086 [mention-bot] Deprecate mention-bot
  .bldr.toml
  mention-bot/README.md
  mention-bot/plan.sh
Labels: A-core-plans, C-deprecation

#2084 [ruby22] Deprecate Ruby22
  .bldr.toml
  ruby22/README.md
  ruby22/plan.sh
Labels: A-core-plans, C-deprecation

#2083 [jdk9/jre9] Deprecate Java9
  .bldr.toml
  jdk9/README.md
  jdk9/plan.sh
  jre9/README.md
  jre9/plan.sh
Labels: A-core-plans, C-deprecation

#2097 [artifactory-pro] Updated artifactory-pro to latest version.
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up
