Repository habitat-sh/core-plans, pull requests merged in 2018-09, with the labels that each got.

#1830 [nghttp2] Update nghttp2 to 1.33.0
  nghttp2/plan.sh
Labels: C-minor-version-up

#1826 [gnatsd] Upgrade to 1.3.0, add README, add tests
  gnatsd/README.md
  gnatsd/plan.sh
  gnatsd/test.bats
  gnatsd/test.sh
Labels: C-minor-version-up

#1818 [nginx] Upgrade nginx to 1.15.3, add tests
  nginx/plan.sh
  nginx/test.bats
  nginx/test.sh
Labels: C-minor-version-up

#1837 [vault] Upgrade to 0.11.1
  vault/plan.sh
  vault/test.bats
  vault/test.sh
Labels: C-minor-version-up

#1838 [nodejs] Update to 10.10.0
  node/plan.sh
  node10/plan.sh
Labels: C-minor-version-up

#1842 [dex] bump v2.10.0 -> v2.11.0
  dex/plan.sh
Labels: C-minor-version-up

#1844 [packer] Update packer to 1.3.0
  packer/plan.sh
Labels: C-minor-version-up

#1845 [node8] Update node8 to 8.12.0
  node8/plan.sh
Labels: C-minor-version-up

#1829 [minio] Update to 2018-09-01T00-38-25Z, add tests
  minio/plan.sh
  minio/tests/test.bats
  minio/tests/test.sh
Labels: C-minor-version-up

#1848 [consul] Update consul to 1.2.3
  consul/plan.sh
Labels: C-minor-version-up

#1849 [libsasl2] New plan for libsasl2
  .bldr.toml
  libsasl2/README.md
  libsasl2/plan.sh
Labels: C-new-plan

#1852 [packer] Upgrade packer to 1.3.1, add simple test
  packer/plan.sh
  packer/tests/test.bats
  packer/tests/test.sh
Labels: C-minor-version-up

#1856 [gocd-server] Upgrade gocd to 18.9.0
  gocd-server/plan.sh
Labels: C-minor-version-up

#1855 [dotnet-core] Upgrade dotnet-core to 2.1.4, add tests
  dotnet-core/plan.sh
  dotnet-core/tests/test.bats
  dotnet-core/tests/test.sh
Labels: C-minor-version-up

#1854 [rust] Update to Rust 1.29.0.
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-core-plans, V-infra

#1859 [pngcrush] New plan for pngcrush
  .bldr.toml
  pngcrush/README.md
  pngcrush/plan.sh
  pngcrush/tests/test.bats
  pngcrush/tests/test.sh
Labels: C-new-plan

#1861 [node] Update nodejs to 10.11.0
  node/plan.sh
  node10/plan.sh
Labels: C-minor-version-up

#1862 [elixir] Update Elixir to 1.7.3, add tests
  elixir/plan.sh
  elixir/tests/test.bats
  elixir/tests/test.sh
Labels: C-minor-version-up

#1736 [cuda] Add new plan
  .bldr.toml
  cuda/README.md
  cuda/plan.sh
Labels: C-new-plan

#1864 [concourse] Rolled concourse and fly forward to 4.2.1
  concourse-fly/plan.sh
  concourse/plan.sh
Labels: C-major-version-up
