Repository habitat-sh/core-plans, pull requests merged in 2018-10, with the labels that each got.

#1866 [kafka] Fix typo in configuration
  kafka/config/server.properties
Labels: C-bug

#1868 [yarn] Upgrade yarn to 1.11.0
  yarn/plan.sh
Labels: C-minor-version-up

#1877 [pngquant] Fix library deps, Upgrade to 2.12.0, add tests
  pngquant/plan.sh
  pngquant/tests/test.bats
  pngquant/tests/test.sh
Labels: C-minor-version-up

#1884 [cabal-install] Rolled cabal-install forward to 2.4.0.0
  cabal-install/plan.sh
Labels: C-minor-version-up, I-linux

#1878 [cockroach] Update CockroachDB to 2.0.6, Add service configuration, Add tests
  cockroach/default.toml
  cockroach/hooks/run
  cockroach/plan.sh
  cockroach/tests/test.bats
  cockroach/tests/test.sh
Labels: C-minor-version-up

#1880 [vim] Update vim to 8.1.0450
  vim/plan.sh
Labels: C-minor-version-up

#1876 [gifsicle] Upgrade gifsicle to 1.91, add tests
  gifsicle/plan.sh
  gifsicle/tests/test.bats
  gifsicle/tests/test.sh
Labels: C-minor-version-up

#1891 [cppcheck] new plan
  .bldr.toml
  cppcheck/README.md
  cppcheck/plan.sh
  cppcheck/tests/test.bats
  cppcheck/tests/test.sh
Labels: C-new-plan

#1886 [nghttp2] Update nghttp2 library to 1.34.0
  nghttp2/plan.sh
Labels: C-minor-version-up

#1896 [vault] Update vault to 0.11.3
  vault/plan.sh
Labels: C-minor-version-up

#1894 [dotnet-asp-core] Adding ASP.NET Core Plan
  .bldr.toml
  CODEOWNERS
  dotnet-asp-core/README.md
  dotnet-asp-core/plan.ps1
  dotnet-asp-core/plan.sh
  dotnet-asp-core/tests/test.bats
  dotnet-asp-core/tests/test.sh
Labels: C-new-plan

#1867 [nginx] Upgrade nginx to 1.15.5
  nginx/plan.ps1
  nginx/plan.sh
Labels: C-minor-version-up

#1873 [cuda-libs] new plan
  .bldr.toml
  CODEOWNERS
  cuda-libs/README.md
  cuda-libs/plan.sh
Labels: C-new-plan

#1898 [libuv] Update libuv to 1.23.2
  libuv/plan.sh
Labels: C-minor-version-up

#1902 [sbt] Update sbt to 1.2.4
  sbt/plan.sh
Labels: C-minor-version-up

#1906 [libtalloc] Updating to 2.1.14
  libtalloc/plan.sh
Labels: C-minor-version-up

#1903 [rust] Update to Rust 1.29.1.
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-core-plans, V-infra

#1881 [artifactory] Smford22/adds artifactory oss
  .bldr.toml
  artifactory/README.md
  artifactory/config/artifactory.default
  artifactory/config/binarystore.xml
  artifactory/config/db.properties
  artifactory/config/server.xml
  artifactory/default.toml
  artifactory/hooks/init
  artifactory/hooks/run
  artifactory/plan.sh
Labels: C-new-plan

#1875 [haproxy] Added newer versions of haproxy and applied RFC_00003
  .bldr.toml
  haproxy/README.md
  haproxy/plan.sh
  haproxy/tests/test.bats
  haproxy/tests/test.sh
  haproxy16/README.md
  haproxy16/config/haproxy.conf
  haproxy16/default.toml
  haproxy16/plan.sh
  haproxy16/tests/test.bats
  haproxy16/tests/test.sh
  haproxy17/README.md
  haproxy17/config/haproxy.conf
  haproxy17/default.toml
  haproxy17/plan.sh
  haproxy17/tests/test.bats
  haproxy17/tests/test.sh
  haproxy18/README.md
  haproxy18/config/haproxy.conf
  haproxy18/default.toml
  haproxy18/plan.sh
  haproxy18/tests/test.bats
  haproxy18/tests/test.sh
Labels: C-minor-version-up, C-new-plan

#1908 [haproxy] Fix for builder building plans
  haproxy/plan.sh
  haproxy16/plan.sh
  haproxy17/plan.sh
  haproxy18/plan.sh
Labels: C-bug

#1907 [consul] Update consul to 1.3.0
  consul/plan.sh
Labels: C-minor-version-up

#1914 [mage] Update mage to 1.7.0, move tests into test directory
  mage/plan.sh
  mage/tests/test.bats
  mage/tests/test.sh
Labels: C-minor-version-up

#1917 [rust] Update to Rust 1.29.2.
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, E-easy, I-linux, I-windows, L-shell, V-core-plans, V-infra

#1910 [Go] Updated Go to 1.11.1 and added tests
  go/README.md
  go/plan.sh
  go/tests/test.bats
  go/tests/test.sh
Labels: C-minor-version-up

#1882 [rabbitmq] Fix log path issue and Elixir dependency, Add tests
  rabbitmq/config/env
  rabbitmq/hooks/init
  rabbitmq/plan.sh
  rabbitmq/tests/test.bats
  rabbitmq/tests/test.sh
Labels: C-bug

#1923 [httpd] Update to 2.4.35, add tests
  httpd/plan.sh
  httpd/tests/test.bats
  httpd/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1922 [mage] Update to 1.7.1
  mage/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1927 [prometheus-cpp] Update version and add CMAKE_FIND_ROOT_PATH
  prometheus-cpp/README.md
  prometheus-cpp/plan.sh
Labels: A-core-plans, V-core-plans

#1929 [terraform] Update to 0.11.9
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1918 [llvm] Upgrade llvm to 7.0.0 and implement RFC3
  .bldr.toml
  llvm/README.md
  llvm/plan.sh
  llvm/tests/test.bats
  llvm/tests/test.sh
  llvm5/README.md
  llvm5/plan.sh
  llvm5/tests/test.bats
  llvm5/tests/test.sh
  llvm7/README.md
  llvm7/plan.sh
  llvm7/tests/test.bats
  llvm7/tests/test.sh
Labels: A-core-plans, C-major-version-up, S-needs-discussion, V-core-plans

#1934 [terraform] Update to 0.11.10
  terraform/plan.sh
Labels: C-minor-version-up

#1938 [vault] Updated vault to 0.11.4
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1936 [artifactory-pro] Updating version and adding tests
  artifactory-pro/plan.sh
  artifactory-pro/tests/helpers.bash
  artifactory-pro/tests/test.bats
  artifactory-pro/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1925 [googletest] Add CMAKE_FIND_ROOT_PATH to make cmake ux better
  googletest/README.md
  googletest/plan.sh
Labels: A-core-plans, C-feature, V-core-plans

#1926 [benchmark] Update version and add CMAKE_FIND_ROOT_PATH
  benchmark/plan.sh
Labels: A-core-plans, C-feature, V-core-plans

#1941 [elixir] Update elixir to 1.7.4
  elixir/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1933 [php] adding intl and zip support for php 7 binary
  php/plan.sh
Labels: A-core-plans, C-feature, V-core-plans

#1944 [libimagequant] Update libimagequant to 2.12.2
  libimagequant/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1945 [pngquant] Update pngquant to 2.12.2
  pngquant/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1942 [opa] add OPA v0.10.0
  .bldr.toml
  opa/README.md
  opa/default.toml
  opa/hooks/run
  opa/plan.sh
  opa/tests/helpers.bash
  opa/tests/test.bats
  opa/tests/test.sh
Labels: A-core-plans, C-new-plan, V-core-plans

#1928 [ansible] Update to 2.6.6, add tests
  ansible/plan.sh
  ansible/tests/test.bats
  ansible/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1949 [packer] Update packer to 1.3.2
  packer/plan.sh
Labels: C-minor-version-up

#1948 [ansible] Update ansible to 2.7.1
  ansible/plan.sh
Labels: C-minor-version-up

#1953 [jffi] Update jffi to 1.2.18
  jffi/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1952 [strace] Update strace to 4.25
  strace/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1943 [jenkins] Upgrade Jenkins to 2.138.2, add tests
  jenkins/plan.sh
  jenkins/tests/test.bats
  jenkins/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#1950 [hugo] Update hugo to 0.50
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans
