Repository habitat-sh/core-plans, pull requests merged in 2019-01, with the labels that each got.

#2162 [packer] Update packer to 1.3.3, windows and linux, add extra run tests
  packer/plan.ps1
  packer/plan.sh
  packer/tests/test.bats
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2133 [cppcheck] Updated cppcheck to 1.86
  cppcheck/plan.sh
Labels: A-core-plans, V-core-plans

#2127 [hugo] Update hugo to 0.53
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2142 [dgraph] Updated dgraph to 1.0.11
  dgraph/plan.sh
Labels: A-core-plans, V-core-plans

#2057 [libxml2] Update libxml2 from 2.9.6 -> 2.9.8
  libxml2/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2037 [restic] add plan
  .bldr.toml
  restic/README.md
  restic/plan.sh
  restic/tests/test.bats
  restic/tests/test.sh
Labels: C-new-plan

#2150 [elasticsearch] Updated elasticsearch to 6.5.4 and added testing.
  elasticsearch/config/jvm.options
  elasticsearch/hooks/health-check
  elasticsearch/plan.sh
  elasticsearch/tests/test.bats
  elasticsearch/tests/test.sh
Labels: A-core-plans, V-core-plans

#2195 [vault] Update vault to 1.0.2
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2197 [Artifactory-Pro] Updated plan to 6.6.5
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#2183 [traefik] Update traefik to 1.7.7
  traefik/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2092 [alsa-lib] Updated alsa-lib to 1.1.7
  alsa-lib/plan.sh
Labels: A-core-plans, V-core-plans

#2044 [mssql] Fix find/patch exec that was attempting to patch non-ELF files
  mssql/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2204 [consul] Update consul to 1.4.1, security update
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2111 [ocaml] Updated ocaml to 4.07.0
  ocaml/plan.sh
Labels: A-core-plans, V-core-plans

#2112 [camlp4] Updated camlp4 to 4.07
  camlp4/plan.sh
Labels: A-core-plans, V-core-plans

#2117 [clingo] Updated clingo to 5.3.0
  clingo/plan.sh
Labels: A-core-plans, V-core-plans

#2093 [ansible] Updated ansible to 2.7.5
  ansible/plan.sh
Labels: A-core-plans, V-core-plans

#2056 [ruby] Update Ruby from 2.5.1 to 2.5.3
  ruby/mkmf-ignore-linker-warnings.patch
  ruby/plan.sh
  ruby25/mkmf-ignore-linker-warnings.patch
  ruby25/plan.sh
Labels: A-core-plans, C-minor-version-up, T-DO-NOT-MERGE, V-core-plans
