Repository habitat-sh/core-plans, pull requests merged in 2019-06, with the labels that each got.

#2603 [go] Update golang to 1.12.5, add trivial test
  go/plan.sh
  go/tests/hello.go
  go/tests/test.bats
  go/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2621 [scaffolding-chef] ensure defaults for run hook are always set if undefined
  scaffolding-chef/lib/scaffolding.sh
  scaffolding-chef/plan.sh
Labels: A-core-plans, A-scaffolding, V-core-plans

#2597 [grpcurl] bump: v1.1.0 -> v1.3.0, add simple test
  grpcurl/plan.sh
  grpcurl/tests/test.bats
  grpcurl/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2384 [clojure] Add Clojure 1.10.0.442
  .bldr.toml
  CODEOWNERS
  clojure/README.md
  clojure/default.toml
  clojure/hooks/run
  clojure/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2627 [apr-util] Tests and README update
  apr-util/README.md
  apr-util/tests/test.bats
  apr-util/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2626 [rust] Update to Rust 1.35.0
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2631 [azure-cli] Add tests and update the README
  azure-cli/README.md
  azure-cli/tests/tests.bats
  azure-cli/tests/tests.sh
Labels: A-core-plans, I-linux, V-core-plans

#2616 [artifactory] [artifactory-pro] Update tests to current standard
  artifactory-pro/README.md
  artifactory-pro/tests/test.sh
  artifactory/README.md
  artifactory/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2618 [rebar3] Update rebar3 to 3.11.0
  rebar3/plan.sh
  rebar3/tests/test.bats
  rebar3/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2614 [alsa-lib] Bump to 1.1.9, add tests
  alsa-lib/README.md
  alsa-lib/plan.sh
  alsa-lib/tests/test.bats
  alsa-lib/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2625 [zsh] Fix non-interactive build, add tests
  zsh/tests/test.bats
  zsh/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2639 [e2fsprogs] Update to 1.45.2 and add modern tests
  e2fsprogs/plan.sh
  e2fsprogs/tests/test.bats
  e2fsprogs/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2600 [filebeat] Update to 7.1.1 + testing + cleanup
  filebeat/config/filebeat.yml
  filebeat/plan.sh
  filebeat/tests/test.bats
  filebeat/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2601 [journalbeat] Update to 7.1.1, update tests
  journalbeat/default.toml
  journalbeat/plan.sh
  journalbeat/tests/test.bats
  journalbeat/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2602 [metricbeat] Update to 7.1.1, update testing
  metricbeat/default.toml
  metricbeat/plan.sh
  metricbeat/tests/test.bats
  metricbeat/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2650 [artifactory] [artifactory-pro] update to artifactory 6.10.3
  artifactory-pro/README.md
  artifactory-pro/plan.sh
  artifactory-pro/tests/test.sh
  artifactory/README.md
  artifactory/plan.sh
  artifactory/tests/test.sh
Labels: A-core-plans, A-plan-build, V-core-plans

#2654 [terraform] Updating Terraform to 0.12.2
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2604 [apr] Addition of tests and README to plan
  apr/README.md
  apr/tests/test.bats
  apr/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2619 [opa] update tests
  opa/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2638 [nginx] Remove deprecated --with-ipv6 configure flag
  nginx/plan.sh
Labels: A-core-plans, I-linux, V-core-plans

#2661 [opa] bump 0.11.0 -> 0.12.0
  opa/plan.sh
Labels: A-core-plans, C-minor-version-up

#2653 [corretto8] Amazon Corretto8 JDK for windows.
  corretto11/plan.ps1
  corretto8/plan.ps1
Labels: A-core-plans, C-new-plan, I-windows, V-core-plans

#2679 [json-c] Add new plan
  .bldr.toml
  CODEOWNERS
  json-c/README.md
  json-c/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2647 [haproxy] Update haproxy to 1.9.8, consolidate testing
  haproxy/plan.sh
  haproxy/tests/test.bats
  haproxy/tests/test.sh
  haproxy16/tests/test.bats
  haproxy16/tests/test.sh
  haproxy17/tests/test.bats
  haproxy17/tests/test.sh
  haproxy18/tests/test.bats
  haproxy18/tests/test.sh
  haproxy19/plan.sh
  haproxy19/tests/test.bats
  haproxy19/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2646 [fontconfig] Cleanup fontconfig plan.sh
  fontconfig/plan.sh
Labels: A-core-plans, V-core-plans

#2655 [gradle] Update to 5.4.1, update tests
  gradle/README.md
  gradle/plan.sh
  gradle/tests/test.bats
  gradle/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2658 [maven] Apache Maven 3.6.1 for Windows
  maven/plan.ps1
Labels: A-core-plans, C-new-plan, I-windows, V-core-plans

#2645 [corretto8] Fix linker issues with Corretto8
  corretto/plan.sh
  corretto8/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2623 [ghc] Updated GHC to 8.6.5
  ghc/plan.ps1
  ghc/plan.sh
  ghc86/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2608 [scaffolding-ruby] Replace dependency on PG server with PG client
  scaffolding-ruby/CHANGELOG.md
  scaffolding-ruby/lib/scaffolding.sh
  scaffolding-ruby/plan.sh
Labels: A-core-plans, A-scaffolding, V-core-plans

#2622 [zstd] Bump to 1.4.0, add dependencies, add tests
  zstd/plan.sh
  zstd/tests/test.bats
  zstd/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2696 [nss] Update to 3.44
  nss/README.md
  nss/plan.sh
Labels: A-core-plans, C-minor-version-up

#2697 [cyrus-sasl] Update to 2.1.27
  cyrus-sasl/README.md
  cyrus-sasl/plan.sh
Labels: A-core-plans, C-minor-version-up

#1771 [mongodb] Simplify configuration, reduce to minimum
  mongodb/README.md
  mongodb/config/mongod.conf
  mongodb/config/mongos.conf
  mongodb/default.toml
  mongodb/plan.sh
Labels: S-needs-discussion, T-DO-NOT-MERGE

#2140 [dejagnu] Updated dejagnu to 1.6.2
  dejagnu/plan.sh
Labels: A-core-plans, C-base-plan, V-core-plans

#2157 [expat] Updated expat to 2.2.6
  expat/plan.sh
Labels: A-core-plans, C-base-plan, V-core-plans

#2159 [file] Updated file to 5.36
  file/plan.sh
  file/tests/test.bats
  file/tests/test.sh
Labels: A-core-plans, C-base-plan, V-core-plans

#2170 [gdbm] Updated gdbm to 1.18.1
  gdbm/plan.sh
  gdbm/tests/test.bats
  gdbm/tests/test.sh
Labels: A-core-plans, C-base-plan, C-minor-version-up

#1981 [wget] Adds support for IRIs
  wget/plan.sh
Labels: C-base-plan, S-needs-discussion, T-DO-NOT-MERGE

#2703 [cyrus-sasl] add tests for cyrus-sasl
  cyrus-sasl/tests/test.bats
  cyrus-sasl/tests/test.sh
Labels: A-core-plans

#2690 [tlog] Research and fix canonical license string
  tlog/plan.sh
Labels: A-core-plans, A-documentation

#2683 [maven] update maven to 3.6.1
  maven/plan.sh
  maven/tests/test.bats
  maven/tests/test.sh
Labels: A-core-plans, A-plan-build, C-minor-version-up

#2699 [artifactory] [artifactory-pro] update to 6.10.4
  artifactory-pro/plan.sh
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up

#2702 [maven] corrected issue with maven not being able to find its executables
  maven/plan.ps1
Labels: A-core-plans, C-bug

#2705 [powershell] bump powershell to 6.2.1
  powershell/plan.ps1
Labels: A-core-plans, C-base-plan, C-minor-version-up

#2708 clean up unnecessary path
  .bldr.toml
Labels: A-core-plans

#2686 [gradle4][gradle5]Fix builds of gradle4 and gradle5
  gradle4/plan.sh
  gradle5/plan.sh
Labels: A-core-plans

#2720 [terraform] Update terraform to 0.12.3
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2722 [protobuf-c] Update protobuf-c to 1.3.2
  protobuf-c/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2732 [artifactory] update artifactory to 6.11.0
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2733 [artifactory-pro] update to artifactory-pro-6.11.0
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2731 [metricbeat] Update metricbeat to 7.2.0
  metricbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2729 [filebeat] Update filebeat to 7.2.0
  filebeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2730 [journalbeat] Update journalbeat to 7.2.0
  journalbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2715 [autogen] Add tests
  autogen/tests/test.bats
  autogen/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans
