Repository habitat-sh/core-plans, pull requests merged in 2019-03, with the labels that each got.

#2313 [Artifactory Pro] Updating Artifactory Pro to 6.8.2
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux

#2337 [caddy] Update caddy to 0.11.5
  caddy/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2336 [jenkins] Update Jenkins to latest LTS 2.150.3
  jenkins/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2335 [packer] Update packer to 1.3.5
  packer/plan.ps1
  packer/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2126 [nginx] Update nginx to 1.15.8
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2115 [cerebro] Updated cerebro to 0.8.1
  cerebro/plan.sh
  cerebro/tests/test.bats
  cerebro/tests/test.sh
Labels: A-core-plans, V-core-plans

#2323 [openssl] Update plans to 1.0.2r to patch the latest CVE
  openssl/plan.ps1
  openssl/plan.sh
Labels: V-core-plans

#2334 [nginx] Added Nginx readme
  nginx/README.md
Labels: A-core-plans, A-documentation, V-core-plans

#2340 [apr] Add missing runtime dependencies
  apr/plan.sh
Labels: A-core-plans, C-bug, I-linux, V-core-plans

#2348 [telegraf] Update telegraf to 1.10.0
  telegraf/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2344 [dd-agent] Update dd-agent to 5.32.1
  dd-agent/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2345 [dgraph] Update dgraph to 1.0.12
  dgraph/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2349 [php] Update PHP to 7.3.3
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2347 [consul] Update consul to 1.4.3, cleanup a bit
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2346 [node] Update node to 11.11.0
  node/plan.ps1
  node/plan.sh
  node11/plan.ps1
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2331 [git] Updated git to 2.21.0.
  git/plan.ps1
  git/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2088 [postgresql11] Provide a PostgreSQL 11 plan
  .bldr.toml
  CODEOWNERS
  postgresql11-client/README.md
  postgresql11-client/plan.ps1
  postgresql11-client/plan.sh
  postgresql11/README.md
  postgresql11/config/functions.sh
  postgresql11/config/pg_hba.conf
  postgresql11/config/pg_ident.conf
  postgresql11/config/postgresql.conf
  postgresql11/config/pwfile
  postgresql11/config/recovery.conf
  postgresql11/default.toml
  postgresql11/docker-compose.yml
  postgresql11/hooks/health_check
  postgresql11/hooks/init
  postgresql11/hooks/reconfigure
  postgresql11/hooks/run
  postgresql11/hooks/suitability
  postgresql11/plan.sh
Labels: A-core-plans, V-core-plans

#2154 [erlang] Updated erlang to 20.2
  erlang/plan.sh
  erlang/tests/test.bats
  erlang/tests/test.sh
Labels: A-core-plans, V-core-plans

#2118 [cmake] Updated cmake to 3.13
  cmake/plan.ps1
  cmake/plan.sh
Labels: A-core-plans, V-core-plans

#2355 [nginx] Version up for Nginx, 1.15.9
  nginx/plan.sh
  nginx/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2257 [prometheus] Update prometheus to 2.7.1
  prometheus/plan.sh
  prometheus2/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2281 [rebar/rebar3] rebar3 update to 3.9.0, deprecate rebar
  .bldr.toml
  rebar/README.md
  rebar3/plan.sh
  rebar3/tests/test.bats
  rebar3/tests/test.sh
Labels: A-core-plans, C-deprecation, C-minor-version-up, V-core-plans

#2359 [rebar/rebar3] Fix incorrect deprecation flag
  rebar/plan.sh
  rebar3/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2343 [openssl] add docs for openssl maintainers
  CONTRIBUTING.md
  openssl/README.md
Labels: A-core-plans, A-documentation, V-core-plans

#2362 [redis3] Update Redis3 to 3.2.13
  redis3/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2364 [libuv] Update libuv to 1.27.0
  libuv/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2365 [node/node11] Update NodeJS to 11.12.0
  node/plan.ps1
  node/plan.sh
  node11/plan.ps1
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2363 [redis4] Update Redis4 to 4.0.14
  redis/plan.sh
  redis4/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2361 [vault] Update Vault to 1.1.0
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#1921 [cockroach] Add CockroachDB clustering support to the habitat plan
  cockroach/README.md
  cockroach/config/ca.crt
  cockroach/config/ca.key
  cockroach/config/client.root.crt
  cockroach/config/client.root.key
  cockroach/default.toml
  cockroach/hooks/health-check
  cockroach/hooks/init
  cockroach/hooks/run
  cockroach/plan.sh
Labels: A-core-plans, C-feature, V-core-plans

#2377 [sbt] Update sbt to 1.2.8, add tests
  sbt/plan.sh
  sbt/tests/test.bats
  sbt/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2358 [journalbeat] add core plan
  .bldr.toml
  CODEOWNERS
  journalbeat/README.md
  journalbeat/config/journalbeat.yml
  journalbeat/default.toml
  journalbeat/hooks/init
  journalbeat/hooks/run
  journalbeat/plan.sh
  journalbeat/tests/test.bats
  journalbeat/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2380 [filebeat] Update filebeat to 6.7.0, minor cleanup
  filebeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2381 [metricbeat] Update metricbeat to 6.7.0, minor cleanup
  metricbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2383 [journalbeat] update journalbeat to 6.7.0, minor style fixes
  journalbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2382 [node10] Update Node10 to 10.15.2 (required for Kibana)
  node10/plan.ps1
  node10/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2367 [strace] Update strace to 5.0
  strace/plan.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2376 [erlang] Update erlang to 21.3
  .bldr.toml
  erlang/plan.sh
  erlang20/README.md
  erlang20/plan.sh
  erlang20/tests/test.bats
  erlang20/tests/test.sh
  erlang21/README.md
  erlang21/plan.sh
  erlang21/tests/test.bats
  erlang21/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2378 [consul] Update consul to 1.4.4
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2379 [elasticsearch] Update elasticsearch to 6.7.0, add more testing
  elasticsearch/plan.sh
  elasticsearch/tests/test.bats
  elasticsearch/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2390 [httpd] Update httpd to 2.4.38, Fix tests to allow for ipv6 listening
  httpd/plan.sh
  httpd/tests/test.bats
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2189 [ipvsadm] New plan for ipvsadm
  .bldr.toml
  ipvsadm/Makefile.patch
  ipvsadm/README.md
  ipvsadm/plan.sh
  ipvsadm/tests/test.bats
  ipvsadm/tests/test.sh
Labels: A-core-plans, C-new-plan, V-core-plans

#2163 [fping] Updated fping to 4.2
  fping/README.md
  fping/plan.sh
  fping/tests/test.bats
  fping/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2391 [corretto] Add corretto
  .bldr.toml
  CODEOWNERS
  corretto/README.md
  corretto/plan.sh
  corretto11/README.md
  corretto11/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2389 [corretto8] Add corretto8
  .bldr.toml
  CODEOWNERS
  corretto8/README.md
  corretto8/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2393 [cabal-install] Added gcc-libs as a runtime dep for cabal-install
  cabal-install/plan.sh
Labels: A-core-plans, C-bug

#2259 [hspec-discover] Added hspec discover plan
  .bldr.toml
  hspec-discover/README.md
  hspec-discover/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2314 [Artifactory] Update to 6.9.0 and added tests
  artifactory/plan.sh
  artifactory/tests/helpers.bash
  artifactory/tests/test.bats
  artifactory/tests/test.sh
Labels: A-core-plans, C-minor-version-up
