Repository habitat-sh/core-plans, pull requests merged in 2019-08, with the labels that each got.

#2939 [hugo] Update hugo to 0.56.3
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2901 [binutils] Update to 2.32
  binutils/ld-wrapper.sh
  binutils/plan.sh
  binutils/tests/test.bats
  binutils/tests/test.sh
Labels: C-base-plan

#2944 [node10] Update node10 to 10.16.1
  node10/plan.ps1
  node10/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2945 [netdata] Update netdata to 1.16.1, add testing
  netdata/plan.sh
  netdata/tests/test.bats
  netdata/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2946 [minio] Update minio to 2019-07-31T18-57-56Z, simplify version check
  minio/plan.sh
  minio/tests/test.bats
  minio/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2913 [consul] Update consul to 1.5.3
  consul/plan.sh
  consul/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2940 [vault] Update vault to 1.1.5, update testing
  vault/plan.sh
  vault/tests/test.bats
  vault/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2943 [terraform] Update terraform to 0.12.6
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2756 [gcc][gcc-libs] Update to 9.1
  bin/ci/build-and-run-tests.sh
  bin/ci/verify-pr-build.sh
  gcc-libs/plan.sh
  gcc/cc-wrapper.sh
  gcc/plan.sh
  gcc/tests/bats/test.bats
  gcc/tests/test.sh
Labels: C-base-plan

#2757 [gmp] Update and add tests
  gmp/plan.sh
  gmp/tests/test.sh
Labels: C-base-plan

#2758 [libmpc] Update build and add tests
  libmpc/plan.sh
  libmpc/tests/test.sh
Labels: C-base-plan

#2760 [mpfr] Update build and add tests
  mpfr/plan.sh
  mpfr/tests/test.sh
Labels: C-base-plan

#2787 [zeromq] Update ZeroMQ libs to 4.3.1
  zeromq/plan.ps1
  zeromq/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2914 [libimagequant] Update libimagequant to 2.12.5
  libimagequant/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2764 [scaffolding-chef] [scaffolding-inspec] deprecate scaffolding-chef and scaffolding-inspec (Merging on 8/1/2019)
  .bldr.toml
  .deprecated/scaffolding-chef/README.md
  .deprecated/scaffolding-chef/lib/scaffolding.sh
  .deprecated/scaffolding-chef/plan.sh
  .deprecated/scaffolding-inspec/lib/scaffolding.sh
  .deprecated/scaffolding-inspec/plan.sh
Labels: A-core-plans, A-scaffolding, C-deprecation

#2617 [libsodium] Update libsodium to 1.0.18
  libsodium/plan.ps1
  libsodium/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, T-DO-NOT-MERGE, V-core-plans

#2864 [visual-build-tools-2017] add nuget build tools to vs 2017
  .bldr.toml
  visual-build-tools-2017/plan.ps1
Labels: A-core-plans, I-windows, V-core-plans

#2960 [telegraf] Update telegraf to 1.11.4
  telegraf/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2961 [node10] Update node10 to 10.16.2
  node10/plan.ps1
  node10/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2962 [node/node12] Update node to 12.8.0
  node/plan.ps1
  node/plan.sh
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2953 [dotnet-core-sdk] Updating Linux/Windows plan to 2.2.401
  dotnet-core-sdk/plan.ps1
  dotnet-core-sdk/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2688 [ghc] add build instructions for maintainers
  ghc/README.md
Labels: A-core-plans, A-documentation

#2959 [vault] Update vault to 1.2.1
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2778 add template for PRs
  .github/PULL_REQUEST_TEMPLATE/major-version-up.md
  .github/PULL_REQUEST_TEMPLATE/minor-version-up.md
  .github/PULL_REQUEST_TEMPLATE/new-plan.md
Labels: A-core-plans

#2846 [bash] Update to latest version
  bash/bash-patches.sh
  bash/plan.sh
  bash/tests/test.bats
  bash/tests/test.sh
Labels: A-core-plans, C-base-plan

#2937 [linux-headers] Update to latest LTS version
  linux-headers/plan.sh
  linux-headers/tests/test.sh
Labels: C-base-plan

#2947 [diffutils] Update to 3.7
  diffutils/plan.sh
  diffutils/tests/fixtures/alpha
  diffutils/tests/fixtures/beta
  diffutils/tests/test.bats
  diffutils/tests/test.sh
Labels: C-base-plan

#2952 [libunistring] update to 0.9.10
  libunistring/plan.sh
Labels: C-base-plan

#2580 [dnsmasq] Adding dnsmasq plan
  dnsmasq/config/dnsmasq.conf
  dnsmasq/plan.sh~HEAD
  dnsmasq/plan.sh~HEAD_0
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2915 [pngquant] Update pngquant to 2.12.5
  pngquant/plan.sh
  pngquant/tests/test.bats
  pngquant/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2990 [node/node12] Update node to 12.9.0
  node/plan.ps1
  node/plan.sh
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2994 [terraform] Updating to 0.12.7
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans
