Repository habitat-sh/core-plans, pull requests merged in 2019-07, with the labels that each got.

#2750 [apr-util] Cleanup apr-util plan
  apr-util/plan.sh
Labels: A-core-plans, I-linux, V-core-plans

#2752 [ansible] Update ansible to 2.8.1
  ansible/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2751 [apr] Update apr to 1.7.0
  apr/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2748 [consul] Update consul to 1.5.2, update tests
  consul/plan.sh
  consul/tests/helpers.bash
  consul/tests/test.bats
  consul/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2747 [artifactory-pro] minor version up 6.11.1
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#2746 [artifactory] minor version up to 6.11.1
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux

#2749 [libuv] Update libuv to 1.30.0
  libuv/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2728 [envconsul] Update envconsul to 0.8.0, add trivial tests
  envconsul/plan.sh
  envconsul/tests/test.bats
  envconsul/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2726 [openresty] Update openresty to 1.15.8.1, add tests
  openresty/plan.sh
  openresty/tests/test.bats
  openresty/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2721 [elixir] Update elixir to 1.9.0, update tests
  elixir/plan.sh
  elixir/tests/test.bats
  elixir/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2725 [nginx] Update nginx to 1.17.1, update linux based tests
  nginx/plan.ps1
  nginx/plan.sh
  nginx/tests/test.bats
  nginx/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2202 [glibc] Don't strip some .so to support debugging
  glibc/plan.sh
Labels: A-core-plans, C-base-plan, S-needs-discussion, T-DO-NOT-MERGE

#2719 [jq-static] Update to jq 1.6 and add tests
  jq-static/plan.ps1
  jq-static/plan.sh
  jq-static/tests/test.bats
  jq-static/tests/test.pester.ps1
  jq-static/tests/test.ps1
  jq-static/tests/test.sh
Labels: A-core-plans, C-minor-version-up

#2517 [ruby23] Deprecate Ruby 2.3
  .bldr.toml
  .deprecated/ruby23/README.md
  .deprecated/ruby23/plan.sh
  ruby23/README.md
  ruby23/mkmf-ignore-linker-warnings.patch
  ruby23/plan.sh
Labels: C-deprecation

#2771 [packer] Update packer to 1.4.2, update tests
  packer/plan.ps1
  packer/plan.sh
  packer/tests/test.bats
  packer/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2768 [caddy] Update Caddy to 1.0.1, update tests
  caddy/plan.sh
  caddy/tests/test.bats
  caddy/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2770 [nettle] Update nettle to 3.5.1
  nettle/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2776 [curl] Update to latest version
  curl/plan.sh
  curl/tests/test.bats
  curl/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux

#2677 [opa] add small test updates and doc to opa
  opa/tests/test.bats
  opa/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2790 [opa] update to 0.12.1
  opa/plan.sh
Labels: A-core-plans, C-minor-version-up

#2779 [curl-static-musl] Update curl-static-musl to 7.65.1
  curl-static-musl/plan.sh
  curl-static-musl/tests/test.bats
  curl-static-musl/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2780 [ansible] Update ansible to 2.8.2
  ansible/plan.sh
  ansible/tests/test.bats
  ansible/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2781 [node] Update node to 12.6.0
  node/plan.ps1
  node/plan.sh
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2782 [httpd] Update httpd to 2.4.39, update test style
  httpd/plan.sh
  httpd/tests/test.bats
  httpd/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2772 [dex] bump to v2.17.0, update test code
  dex/plan.sh
  dex/tests/test.bats
  dex/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux

#2783 [gdb] Update gdb to 8.3, update test style
  gdb/plan.sh
  gdb/tests/test.bats
  gdb/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2785 [php] Update PHP to 7.3.7
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2786 [netdata] Update Netdata repo
  netdata/README.md
  netdata/plan.sh
Labels: A-core-plans, I-linux, V-core-plans

#2791 [rabbitmq] Update RabbitMQ to 3.7.16, update test style
  rabbitmq/plan.sh
  rabbitmq/tests/test.bats
  rabbitmq/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2598 [lastpass-cli] Adding lastpass-cli
  .bldr.toml
  lastpass-cli/README.md
  lastpass-cli/patches/Makefile_add_curl_opts.patch
  lastpass-cli/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2693 [libpipeline] update libpipeline to 1.5.1, fix minor formatting
  libpipeline/README.md
  libpipeline/plan.sh
Labels: A-core-plans, C-minor-version-up

#2805 [netdata] Update netdata to 1.16.0
  netdata/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2547 [grub] Fix failing grub build adding core dependencies
  grub/plan.sh
  grub/tests/test.bats
  grub/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2695 [atk] minor version update 2.28.1
  atk/plan.sh
Labels: A-core-plans, C-minor-version-up

#2734 [zlib] Add tests to zlib (base plan refresh)
  zlib/tests/test.bats
  zlib/tests/test.sh
Labels: C-base-plan

#2777 [opendistro-for-elasticsearch] blacklist the build-test process
  bin/ci/build-and-run-tests.sh
Labels: I-linux

#2800 [node10] Update node10 to 10.16.0 and add tests
  node/tests/test.bats
  node/tests/test.pester.ps1
  node/tests/test.ps1
  node/tests/test.sh
  node10/plan.ps1
  node10/plan.sh
  node10/tests/test.bats
  node10/tests/test.pester.ps1
  node10/tests/test.ps1
  node10/tests/test.sh
  node11/tests/test.bats
  node11/tests/test.pester.ps1
  node11/tests/test.ps1
  node11/tests/test.sh
  node12/tests/test.bats
  node12/tests/test.pester.ps1
  node12/tests/test.ps1
  node12/tests/test.sh
  node6/tests/test.bats
  node6/tests/test.pester.ps1
  node6/tests/test.ps1
  node6/tests/test.sh
  node8/tests/test.bats
  node8/tests/test.pester.ps1
  node8/tests/test.ps1
  node8/tests/test.sh
  node9/tests/test.bats
  node9/tests/test.pester.ps1
  node9/tests/test.ps1
  node9/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows

#2809 [php] Update bison dependency
  php/plan.sh
Labels: A-core-plans

#2802 Update testing standard
  docs/dev/policy_documents/standards-for-tests.md
Labels: A-core-plans, A-documentation

#2818 [man-pages] Update to latest version
  man-pages/plan.sh
Labels: A-core-plans, C-minor-version-up

#2832 [terraform] Updating to 0.12.4
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2817 [tor] Update to latest version
  tor/config/torrc
  tor/plan.sh
Labels: A-core-plans, C-minor-version-up

#2812 [dpkg] Update version
  dpkg/plan.sh
  dpkg/tests/test.bats
  dpkg/tests/test.sh
Labels: A-core-plans, C-minor-version-up

#2819 [mono4] Deprecate package
  .bldr.toml
  .deprecated/mono4/README.md
  .deprecated/mono4/plan.sh
  mono4/README.md
Labels: A-core-plans, C-deprecation

#2843 [flex] Add simple test
  flex/plan.sh
  flex/tests/test.bats
  flex/tests/test.sh
Labels: C-base-plan

#2847 [procps-ng] Fix license, add tests
  procps-ng/plan.sh
  procps-ng/tests/test.bats
  procps-ng/tests/test.sh
Labels: C-base-plan

#2842 [vim] Update to latest release
  vim/plan.sh
  vim/tests/test.bats
  vim/tests/test.sh
Labels: C-base-plan, T-DO-NOT-MERGE

#2793 [patchelf] Update to 0.10
  patchelf/plan.sh
  patchelf/tests/test.bats
  patchelf/tests/test.sh
Labels: A-core-plans, C-base-plan

#2858 [readline] Update to 8.0
  readline/plan.sh
  readline/readline-patches.sh
  readline/tests/test.bats
  readline/tests/test.sh
Labels: C-base-plan

#2840 [shadow] Update to 4.7, add test
  shadow/plan.sh
  shadow/tests/test.bats
  shadow/tests/test.sh
Labels: C-base-plan

#2753 [file] Update file to 5.37, update tests
  file/plan.sh
  file/tests/test.bats
  file/tests/test.sh
Labels: C-base-plan

#2855 [dotnet-asp-core] Updated Linux/Windows plans to 2.2.6
  dotnet-asp-core/plan.ps1
  dotnet-asp-core/plan.sh
Labels: A-core-plans, C-minor-version-up, I-windows, V-core-plans

#2841 [psmisc] Update to 23.2, add tests
  psmisc/plan.sh
  psmisc/tests/test.bats
  psmisc/tests/test.sh
Labels: C-base-plan

#2836 [busybox][busybox-static] Update to 1.31
  busybox-static/plan.sh
  busybox-static/tests/test.bats
  busybox-static/tests/test.sh
  busybox/config
  busybox/plan.sh
  busybox/tests/test.bats
  busybox/tests/test.sh
Labels: C-base-plan

#2834 [python-minimal] New plan
  .bldr.toml
  CODEOWNERS
  base-plans.txt
  python-minimal/README.md
  python-minimal/plan.sh
  python-minimal/tests/test.sh
Labels: A-core-plans

#2811 [bison2] Deprecate package
  .bldr.toml
  .deprecated/bison2/README.md
  .deprecated/bison2/plan.sh
  bison2/README.md
Labels: A-core-plans, C-deprecation

#2773 [cmake] Fix so that builds in windows studio
  cmake/plan.ps1
  cmake/tests/test.bats
  cmake/tests/test.pester.ps1
  cmake/tests/test.ps1
  cmake/tests/test.sh
Labels: A-core-plans, I-windows

#2865 [elixir] Update elixir to 1.9.1
  elixir/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2866 [terraform] Update terraform to 0.12.5
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2869 [strace] Update strace to 5.2
  strace/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2862 [tar] Update to 1.32, remove test patch, add BATS test
  tar/README.md
  tar/plan.sh
  tar/skip-test.patch
  tar/tests/test.bats
  tar/tests/test.sh
Labels: A-core-plans, C-base-plan, I-linux, V-core-plans

#2885 [artifactory] minor version up 6.11.3
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up

#2886 [artifactory-pro] minor version up 6.11.3
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#2769 [scaffolding-gradle] Update gradle scaffolding URI
  scaffolding-gradle/plan.sh
Labels: A-core-plans, V-core-plans

#2856 [sumologic] Replace jdk with openjdk
  sumologic/hooks/run
  sumologic/plan.sh
  sumologic/test.sh
  sumologic/tests/test.bats
  sumologic/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2889 [dotnet-core-sdk] Updating Linux/Windows plans to 2.2.301 w/new tests
  dotnet-core-sdk/plan.ps1
  dotnet-core-sdk/plan.sh
  dotnet-core-sdk/tests/test.bats
  dotnet-core-sdk/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2894 [cerebro] Update Cerebro to 0.8.4, update tests, migrate to openjdk
  cerebro/config/application.conf
  cerebro/plan.sh
  cerebro/tests/test.bats
  cerebro/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2867 [cockroach] Update cockroach to 19.1.3, Update tests
  cockroach/plan.sh
  cockroach/tests/test.bats
  cockroach/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2852 [sbt] Replace jdk with openjdk
  sbt/README.md
  sbt/plan.sh
  sbt/tests/test.bats
  sbt/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2763 [bison] Update to 3.4.1
  bison/plan.sh
  bison/tests/test.bats
  bison/tests/test.sh
Labels: C-base-plan

#2795 [attr] Update license string
  attr/plan.sh
  attr/tests/test.bats
  attr/tests/test.sh
Labels: A-core-plans, C-base-plan

#2897 [telegraf] Update telegraf to 1.11.3
  telegraf/plan.sh
  telegraf/tests/test.bats
  telegraf/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2649 [docs] Update standards-for-tests.md to use core/pester [version 2]
  docs/dev/policy_documents/standards-for-tests.md
Labels: A-core-plans, A-documentation, V-core-plans

#2745 [bzip2, perl, openssl] add runtime dep for 2015 cpp redistributable
  bzip2/plan.ps1
  openssl/plan.ps1
  perl/plan.ps1
Labels: T-DO-NOT-MERGE

#2667 [cacerts] Add tests to the core/cacerts for windows and linux
  cacerts/tests/test.bats
  cacerts/tests/test.pester.ps1
  cacerts/tests/test.ps1
  cacerts/tests/test.sh
Labels: C-base-plan

#2908 [hugo] Update hugo to 0.56.1
  hugo/plan.sh
  hugo/tests/test.bats
  hugo/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2903 [sccache] Update sccache to 0.2.9, add tests, fix build, add features
  sccache/plan.sh
  sccache/tests/test.bats
  sccache/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2896 [node] Update node to 12.7.0
  node/plan.ps1
  node/plan.sh
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2895 [nginx] Update nginx to 1.17.2
  nginx/plan.ps1
  nginx/plan.sh
  nginx/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2871 Update dgraph to 1.0.16, update tests
  dgraph/plan.sh
  dgraph/tests/test.bats
  dgraph/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2859 [scaffolding-go] Go Module Mode
  .gitignore
  scaffolding-go/README.md
  scaffolding-go/lib/go_module.sh
  scaffolding-go/lib/gopath_mode.sh
  scaffolding-go/lib/scaffolding.sh
  scaffolding-go/plan.sh
Labels: A-core-plans, A-scaffolding, V-core-plans

#2806 [perl] Add tests to core/perl
  perl/plan.ps1
  perl/tests/test.bats
  perl/tests/test.pester.ps1
  perl/tests/test.ps1
  perl/tests/test.sh
Labels: C-base-plan

#2870 [yarn] Update yarn to 1.17.3, update tests
  yarn/plan.sh
  yarn/tests/test.bats
  yarn/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2923 [iana-etc] Update license string
  iana-etc/plan.sh
  iana-etc/tests/test.sh
Labels: C-base-plan

#2925 [autoconf] Update license string
  autoconf/plan.sh
  autoconf/tests/test.bats
  autoconf/tests/test.sh
Labels: C-base-plan

#2928 [make] Update license string
  make/plan.sh
  make/tests/fixtures/Makefile
  make/tests/test.bats
  make/tests/test.sh
Labels: C-base-plan
