Repository habitat-sh/core-plans, pull requests merged in 2019-11, with the labels that each got.

#3107 [packer] Update packer to 1.4.5
  packer/plan.ps1
  packer/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3104 [terraform] Update terraform to 0.12.13
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3106 [pester] Pester package for linux
  pester/README.md
  pester/plan.sh
  pester/tests/test.bats
  pester/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3119 [libxslt] Update from 1.1.33 to 1.1.34 to resolve CVE-2019-13117
  libxslt/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, T-security, V-core-plans

#3118 [libxml2] Update from 2.9.9 to 2.9.10
  libxml2/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3099 [ghc86] Added ghc86 plan for windows
  ghc86/plan.ps1
Labels: A-core-plans, C-new-plan, I-windows

#3103 [alex] Fix alex builds for ghc 8.8
  alex/plan.sh
Labels: A-core-plans, I-linux, V-core-plans

#3102 [happy] Updated happy to 1.19.12
  happy/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux

#3101 [shellcheck] Updated shellcheck to 0.7.0
  shellcheck/plan.ps1
  shellcheck/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows

#3122 [haproxy] Update HAProxy to 2.0.9
  haproxy/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3105 [hugo] Update hugo to 0.59.1
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3139 [bash-completion] Update bash-completion to 2.9
  bash-completion/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3137 [autogen] Minor cleanup for autogen
  autogen/plan.sh
  autogen/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#3133 [alex] Update alex to 3.2.5, improve testing
  alex/plan.sh
  alex/tests/test.bats
  alex/tests/test.sh
  alex/tests/test.x
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3140 [googletest] Update googletest to 1.10.0
  googletest/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans
