Repository habitat-sh/core-plans, pull requests merged in 2019-04, with the labels that each got.

#2410 [contributing.md] minor fix for shellcheck rules
  CONTRIBUTING.md
Labels: A-core-plans, A-documentation, V-core-plans

#2405 add echohack to CODEOWNERS for elastic projects [filebeat] [metricbeat] [journalbeat] [elasticsearch]
  CODEOWNERS
Labels: A-core-plans, V-core-plans

#2398 [luajit] Change LuaJIT plan name to luajit
  luajit/plan.sh
  luajit/tests/test.bats
  luajit/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans

#2412 [Artifactory Pro] Updated to 6.9.0
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up

#2407 [cerebro] Update Cerebro to 0.8.2, reduce testing wait
  cerebro/plan.sh
  cerebro/tests/test.bats
  cerebro/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2408 [openjpeg] Update openjpeg to 2.3.1
  openjpeg/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2411 [dotnet-asp-core] Updated plans to 2.2.3
  dotnet-asp-core/plan.ps1
  dotnet-asp-core/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2395 [node/node11] Update node to 11.13.0
  node/plan.ps1
  node/plan.sh
  node11/plan.ps1
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2409 Update telegraf to 1.10.2, add minimal service test
  telegraf/plan.sh
  telegraf/tests/test.bats
  telegraf/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2417 [elsaticsearch] Update elasticsearch to 6.7.1
  elasticsearch/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2422 [dotnet-core] Updated Linux and Windows plans to 2.2.3
  dotnet-core/plan.ps1
  dotnet-core/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2424 [cerebro] Update cerebro to 0.8.3, standardize testing
  cerebro/plan.sh
  cerebro/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2371 [libmaxminddb] Added the libmaxminddb plan.
  .bldr.toml
  libmaxminddb/README.md
  libmaxminddb/plan.sh
  libmaxminddb/tests/test.bats
  libmaxminddb/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2432 [hugo] Update hugo to 0.55.0 - Add more complete testing
  hugo/plan.sh
  hugo/tests/test.bats
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2426 [dotnet-472-dev-pack] Include all required metadata
  .bldr.toml
  dotnet-472-dev-pack/plan.ps1
Labels: C-bug

#2444 [dotnet-472-dev-pack] Fix download URL
  dotnet-472-dev-pack/plan.ps1
Labels: I-windows, S-awaiting-review

#2441 [filebeat] minor version up 6.7.1
  filebeat/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2439 [metricbeat] minor version up 6.7.1
  metricbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2440 [journalbeat] minor version up 6.7.1
  journalbeat/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2452 [rust] Bump to 1.34.0
  .bldr.toml
  rust/plan.ps1
  rust/plan.sh
Labels: C-minor-version-up

#2447 [vault] Upgrade vault to 1.1.1
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2094 [ant] Updated ant to 1.10.5
  ant/README.md
  ant/plan.sh
  ant/tests/test.bats
  ant/tests/test.sh
Labels: A-core-plans, V-core-plans

#2425 [dotnet-471-dev-pack] Include all required metadata
  .bldr.toml
  dotnet-471-dev-pack/plan.ps1
Labels: C-bug

#2366 [reportviewer2010] adds the MS report viewer 2010 redistributable assemblies
  reportviewer2010/README.md
  reportviewer2010/plan.ps1
Labels: A-core-plans, C-new-plan, I-windows, V-core-plans

#2449 [systemd] Upgrade systemd to 242
  systemd/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2442 [nginx] Update nginx to 1.15.11
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2450 [rabbitmq] Upgrade rabbitmq to 3.7.14
  rabbitmq/plan.sh
  rabbitmq/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2451 [tap-xunit] Added tap-xunit
  .bldr.toml
  tap-xunit/README.md
  tap-xunit/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2457 [prometheus] Update prometheus to 2.9.0
  prometheus/plan.sh
  prometheus2/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2456 [libpng] Update libpng to 1.6.37
  libpng/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2455 [haproxy] Update HAProxy to 1.9.6
  haproxy/plan.sh
  haproxy19/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2448 [tmux] Upgrade tmux to 2.8, add tests
  tmux/plan.sh
  tmux/tests/test.bats
  tmux/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2406 [python] adding windows python plans
  python/plan.ps1
  python2/plan.ps1
  python34/plan.ps1
  python36/plan.ps1
  python37/plan.ps1
Labels: A-core-plans, C-new-plan, I-windows

#2465 [rebar3] Update rebar3 to 3.10.0
  rebar3/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2464 [memcached] Update memcached to 1.5.13, add do_check
  memcached/plan.sh
  memcached/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2466 [ripgrep] Update ripgrep to 11.0.1, add tests
  ripgrep/plan.sh
  ripgrep/tests/test.bats
  ripgrep/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2467 [telegraf] Update telegraf to 1.10.3
  telegraf/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2468 [prometheus] Update prometheus to 2.9.1
  prometheus/plan.sh
  prometheus2/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2469 [nginx] Update nginx to 1.15.12
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2470 [gnatsd] Update gnatsd to 1.4.1
  gnatsd/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2472 [minio] Update minio to 2019-04-09T01-22-30Z, fix tests for IPv6
  minio/plan.sh
  minio/tests/test.bats
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2476 [hugo] Update hugo to 0.55.2
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2489 [Artifactory Pro] Updating to 6.9.1
  artifactory-pro/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2490 [Artifactory] Updating to 6.9.1
  artifactory/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2268 [grpc-cpp] add new plan
  .bldr.toml
  grpc-cpp/README.md
  grpc-cpp/no_ipv6_port_server.patch
  grpc-cpp/plan.sh
Labels: A-core-plans, C-new-plan, V-core-plans

#2492 [hugo] Update hugo to 0.55.4
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2515 [scaffolding-chef] copy data_bags directory
  scaffolding-chef/lib/scaffolding.sh
Labels: A-core-plans, A-scaffolding, V-core-plans

#2495 [nginx] Update Nginx to 1.16.0
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2529 [memcached] Update memcached to 1.5.14
  memcached/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2508 [prometheus] Update prometheus to 2.9.2
  prometheus/plan.sh
  prometheus2/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans
