Repository habitat-sh/core-plans, pull requests merged in 2019-10, with the labels that each got.

#3044 [yarn] Update yarn to 1.18.0
  yarn/plan.ps1
  yarn/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3043 [telegraf] Update telegraf to 1.12.2
  telegraf/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3025 [maven] Update maven to 3.6.2
  maven/plan.ps1
  maven/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3020 [php] Update PHP to 7.3.9
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3019 [netdata] Update netdata to 1.17.0
  netdata/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3017 [jffi] Update jffi to 1.2.20
  jffi/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3016 [ant] Update ant to 1.10.7
  ant/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3042 [nginx] Update nginx to 1.17.4
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3050 [php] Update PHP to 7.3.10
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3049 [strace] Update strace to 5.3
  strace/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3052 [protobuf-cpp] Update protobuf-cpp to 3.9.2
  protobuf-cpp/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3054 [memcached] Update memcached to 1.5.19
  memcached/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3055 [packer] Update packer to 1.4.4
  packer/plan.ps1
  packer/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3056 [tcpdump] Update tcpdump to 4.9.3, add simple tests
  tcpdump/plan.sh
  tcpdump/tests/test.bats
  tcpdump/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2997 [libatomic_ops] Upgrade to version 7.6.10
  libatomic_ops/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3063 [asciinema] Add new plan
  .bldr.toml
  CODEOWNERS
  asciinema/README.md
  asciinema/plan.ps1
  asciinema/plan.sh
  asciinema/tests/test.bats
  asciinema/tests/test.sh
Labels: A-core-plans, C-new-plan, V-core-plans

#3062 [jffi] Update jffi to 1.2.21
  jffi/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3061 [yarn] Update yarn to 1.19.1
  yarn/plan.ps1
  yarn/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3069 [consul] Update consul to 1.6.1
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3068 [terraform] Update terraform to 0.12.10
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3077 [haproxy] Update HAProxy to 2.0.7, add prometheus metrics export support
  haproxy/plan.sh
  haproxy/tests/test.bats
  haproxy/tests/test.sh
  haproxy20/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3070 [ansible] Update ansible to 2.8.6
  ansible/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3071 [bind] Update bind to 9.15.4
  bind/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3051 [protobuf] Update protobuf to 3.9.2, add tests
  protobuf/plan.ps1
  protobuf/plan.sh
  protobuf/tests/test.bats
  protobuf/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3073 [docker] Update docker for linux to 19.03.3, add tests
  docker/plan.sh
  docker/tests/test.bats
  docker/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#3082 [nss-myhostname] add a new plan!
  .bldr.toml
  CODEOWNERS
  nss-myhostname/README.md
  nss-myhostname/plan.sh
Labels: C-new-plan, I-linux

#3088 [dcrpm] Add new plan
  .bldr.toml
  CODEOWNERS
  dcrpm/README.md
  dcrpm/plan.sh
  dcrpm/tests/test.bats
  dcrpm/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3089 [haproxy] Update HAProxy to 2.0.8
  haproxy/plan.sh
  haproxy20/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3072 [composer] Update composer to 1.9.0, add tests
  composer/plan.sh
  composer/tests/test.bats
  composer/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3080 [nginx-prometheus-exporter] Add new plan: nginx-prometheus-exporter
  .bldr.toml
  nginx-prometheus-exporter/README.md
  nginx-prometheus-exporter/default.toml
  nginx-prometheus-exporter/hooks/run
  nginx-prometheus-exporter/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3091 [jenkins] Update jenkins to 2.190.2
  jenkins/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3092 [jffi] Update jffi to 1.2.22
  jffi/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3081 [node_exporter] Update node_exporter to 0.18.1, update config, use new command invoca…
  node_exporter/default.toml
  node_exporter/hooks/run
  node_exporter/plan.sh
  node_exporter/tests/test.bats
  node_exporter/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3079 [prometheus] Update prometheus to 2.13.1
  prometheus/plan.sh
  prometheus/tests/test.bats
  prometheus/tests/test.sh
  prometheus2/plan.sh
  prometheus2/tests/test.bats
  prometheus2/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3093 [grafana-loki] add new plan
  .bldr.toml
  grafana-loki/README.md
  grafana-loki/config/config.yaml
  grafana-loki/default.toml
  grafana-loki/plan.sh
  grafana-loki/tests/test.bats
  grafana-loki/tests/test.sh
  grafana/README.md
  grafana/config/datasource-loki.yaml
  grafana/hooks/post-run
  grafana/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3094 [grafana-promtail] add new plan
  .bldr.toml
  grafana-promtail/README.md
  grafana-promtail/config/config.yaml
  grafana-promtail/default.toml
  grafana-promtail/plan.sh
  grafana-promtail/tests/test.bats
  grafana-promtail/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans
