Repository habitat-sh/core-plans, pull requests merged in 2019-05, with the labels that each got.

#2507 [caddy] Update Caddy to 1.0.0, skip version check due to upstream bug
  caddy/plan.sh
  caddy/tests/test.bats
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2528 Update yarn to 1.16.0
  yarn/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2540 [hugo] Update hugo to 0.55.5, implement new testing style
  hugo/plan.sh
  hugo/tests/test.bats
  hugo/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2553 [ant] Update ant to 1.10.6, and update tests
  ant/plan.sh
  ant/tests/test.bats
  ant/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2496 [lz4] Update lz4 to 1.9.1
  lz4/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2564 [scaffolding-chef] automatically accept license for chef15
  scaffolding-chef/lib/scaffolding.sh
  scaffolding-chef/plan.sh
Labels: A-core-plans, V-core-plans

#2567 [ruby26] Update to 2.6.3
  ruby26/plan.sh
Labels: C-minor-version-up

#2568 [libyaml] Update to 0.1.7
  libyaml/plan.sh
Labels: C-minor-version-up

#2539 Add dev policy document for testing standards
  docs/dev/README.md
  docs/dev/policy_documents/standards-for-tests.md
  docs/dev/policy_documents/testing-pull-requests.md
Labels: A-documentation

#2497 [node/node12] Add node12, update node to node12
  .bldr.toml
  node/plan.ps1
  node/plan.sh
  node12/README.md
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, I-windows, V-core-plans

#2576 [terraform] Update to 0.11.14
  terraform/plan.sh
  terraform/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2583 [sassc] Update sassc to 3.6.0
  sassc/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2582 [hugo] Update hugo to 0.55.6
  hugo/plan.sh
  hugo/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2590 [sassc] Fix version info in build, add tests
  sassc/plan.sh
  sassc/tests/test.bats
  sassc/tests/test.sh
Labels: A-core-plans, C-bug, I-linux, V-core-plans

#2592 [terraform] Update to 0.12.0, update test approach
  terraform/plan.sh
  terraform/tests/test.bats
  terraform/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#2586 [kafka] Set topic replication factor
  kafka/config/server.properties
Labels: A-core-plans, C-bug, V-core-plans

#2588 [netdata] Update netdata to 1.15.0
  netdata/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2610 [php] Update to 7.3.5, refactor test runner
  php/plan.sh
  php/test/libzip_support.php
  php/test/test.sh
  php/tests/libzip_support.php
  php/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2611 [tmux] Update tmux to 2.9a, update tests
  tmux/plan.sh
  tmux/tests/test.bats
  tmux/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2609 [bind] Update to 9.14.2, add tests
  bind/README.md
  bind/plan.sh
  bind/tests/test.bats
  bind/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2605 [netdata] Update checksum for republished version
  netdata/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2607 [kafka] Update download location
  kafka/plan.sh
Labels: A-core-plans, C-bug, I-linux, V-core-plans
