Repository habitat-sh/core-plans, pull requests merged in 2019-09, with the labels that each got.

#3000 [git] Upgrade git to 2.23
  git/plan.ps1
  git/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3002 [rsync] Upgrade rsync to 3.1.3
  rsync/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3015 [terraform] Updating to 0.12.8
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2996 [go] Update to version 1.12.9
  go/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3014 [hugo] Update hugo to 0.58.1
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3018 [consul] Update consul to 1.6.0
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3027 [libfastjson] Added libfastjson
  .bldr.toml
  libfastjson/README.md
  libfastjson/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans
