Repository habitat-sh/core-plans, pull requests merged in 2019-02, with the labels that each got.

#2148 [dpkg] Updated dpkg to 1.19.2
  dpkg/plan.sh
  dpkg/tests/test.bats
  dpkg/tests/test.sh
Labels: A-core-plans, V-core-plans

#2137 [curl] Updated curl to 7.63.0
  curl-static-musl/plan.sh
  curl-static-musl/tests/test.bats
  curl-static-musl/tests/test.sh
  curl/plan.sh
  curl/tests/test.bats
  curl/tests/test.sh
Labels: A-core-plans, V-core-plans

#2252 [dpkg] Update dpkg from 1.19.2 -> 1.19.4
  dpkg/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2129 [jenkins] Update jenkins to 2.150.1, add extra timeout for service load
  jenkins/plan.sh
  jenkins/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2130 [zstd] Update zstd to 1.3.8
  zstd/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2138 [dbus] Updated dbus to 1.13.8
  dbus/plan.sh
  dbus/tests/test.bats
  dbus/tests/test.sh
Labels: A-core-plans, V-core-plans

#2131 [zsh] Update ZSH to 5.6.2
  zsh/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2136 [curator] Updated curator to 5.6.0
  curator/plan.sh
  curator/tests/test.bats
  curator/tests/test.sh
  curator4/plan.sh
Labels: A-core-plans, V-core-plans

#2145 [docker-compose] Updated docker-compose to 1.23.2
  docker-compose/plan.sh
  docker-compose/tests/test.bats
  docker-compose/tests/test.sh
Labels: A-core-plans, V-core-plans

#2155 [eudev] Updated eudev to 3.2.7
  eudev/plan.sh
Labels: A-core-plans, V-core-plans

#2109 [cabal-install] Updated cabal-install to 2.4.1.0
  cabal-install/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2123 [node/node11] Update Node and Node11 to 11.6.0
  node/plan.ps1
  node/plan.sh
  node11/plan.ps1
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2095 [apr] Updated apr to 1.6.5
  apr/plan.sh
Labels: A-core-plans, V-core-plans

#2110 [cairo] Updated cairo to 1.16.0
  cairo/plan.sh
Labels: A-core-plans, V-core-plans

#2105 [boringssl] Updated boringssl to 3538
  boringssl/plan.sh
Labels: A-core-plans, V-core-plans

#2164 [freetds] Updated freetds to 1.00.109
  freetds/plan.sh
Labels: A-core-plans, C-minor-version-up

#2246 [buildkite-agent] Update buildkite-agent to 3.8.4
  buildkite-agent/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2146 [dovecot] Updated dovecot to 2.3.4
  dovecot/plan.sh
  dovecot/tests/test.bats
  dovecot/tests/test.sh
Labels: A-core-plans, V-core-plans

#2147 [doxygen] Updated doxygen to 1.8.15
  doxygen/plan.sh
  doxygen/tests/test.bats
  doxygen/tests/test.sh
Labels: A-core-plans, V-core-plans

#2190 [dex] bump v2.13.0 -> v2.14.0, declutter plan.sh
  dex/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2165 [freetype] Updated freetype to 2.9.1
  freetype/plan.sh
Labels: A-core-plans, C-minor-version-up

#2198 [ansible] Update Ansible to 2.7.6
  ansible/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2141 [devicemapper] Updated devicemapper to 2.03.00
  devicemapper/plan.sh
  devicemapper/tests/test.bats
  devicemapper/tests/test.sh
Labels: A-core-plans, V-core-plans

#2237 [nss] Adds gcc-libs dep for nss
  nss/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2124 [node10] Update node10 to 10.15.0
  node10/plan.ps1
  node10/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2055 [libarchive] Update libarchive from 3.3.2 to 3.3.3
  libarchive/plan.ps1
  libarchive/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2185 [php] Update PHP to 7.3.1
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2278 [telegraf] Update telegraf to 1.9.4, add tests
  telegraf/plan.sh
  telegraf/tests/test.bats
  telegraf/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2125 [node8] Update node8 to 8.15.0
  node8/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2121 [concourse-fly] Updated concourse concourse-fly to 4.2.2
  concourse-fly/plan.sh
  concourse/plan.ps1
  concourse/plan.sh
Labels: A-core-plans, V-core-plans

#2239 [llvm5][clang5] Deprecate llvm5 and clang5
  .bldr.toml
  clang5/README.md
  clang5/plan.sh
  llvm5/README.md
  llvm5/plan.sh
Labels: A-core-plans, C-deprecation

#2293 [dpkg] Fixed missing runtime deps
  dpkg/plan.sh
Labels: A-core-plans, C-bug, I-linux

#2192 [elixir] Update Elixir to 1.8.0
  elixir/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2194 [gnatsd] Update gnatsd to 1.4.0, extend test sleep delay
  gnatsd/plan.sh
  gnatsd/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2236 [ansible] Move OpenSSL dep
  ansible/plan.sh
  ansible/tests/test.sh
Labels: A-core-plans, C-bug, V-core-plans

#2295 [scaffolding-inspec] first stab at an inspec scaffolding
  .bldr.toml
  scaffolding-inspec/lib/scaffolding.sh
  scaffolding-inspec/plan.sh
Labels: A-core-plans, A-scaffolding, V-core-plans

#2292 [rpm] Added missing runtime deps for RPM and updated to 4.14.2.1
  rpm/plan.sh
Labels: A-core-plans, C-bug, C-minor-version-up, I-linux

#2290 [sensu] Update to 1.6.2 and fix library linking issues
  sensu/Gemfile
  sensu/README.md
  sensu/hooks/run
  sensu/plan.sh
Labels: A-core-plans, C-bug, C-minor-version-up, I-linux

#2104 [boost] Updated boost to 1.69.0
  boost/plan.sh
Labels: A-core-plans, V-core-plans

#2090 [llvm] Updated llvm to 7.0.1
  llvm/plan.sh
  llvm7/plan.sh
Labels: A-core-plans, V-core-plans

#2276 [caddy] Update caddy 0.11.3, add tests
  caddy/plan.sh
  caddy/tests/test.bats
  caddy/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2188 [libnl] Added libnl, Netlink Protocol
  .bldr.toml
  libnl/plan.sh
  libnl/tests/test.bats
  libnl/tests/test.sh
Labels: A-core-plans, C-new-plan, V-core-plans

#2263 [hugo] Update hugo to 0.54.0
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2253 [direnv] Update direnv to 1.19.1, add tests
  direnv/plan.sh
  direnv/tests/test.bats
  direnv/tests/test.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2242 [leveldb] Add gcc libs
  leveldb/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2243 [libfcgi] Add gcc libs to deps
  libfcgi/plan.sh
Labels: A-core-plans, C-bug, V-core-plans

#2151 [elasticsearch] Updated elasticsearch5 to 5.6.14
  elasticsearch5/plan.sh
Labels: A-core-plans, V-core-plans

#2100 [bdwgc] Updated bdwgc to 8.0.0
  .bldr.toml
  bdwgc/plan.sh
  bdwgc7/README.md
  bdwgc7/plan.sh
  bdwgc8/README.md
  bdwgc8/plan.sh
Labels: A-core-plans, C-major-version-up, V-core-plans

#2174 [git] Updated git to 2.20.1
  git/plan.ps1
  git/plan.sh
  git/tests/test.bats
  git/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2264 [openresty] Update OpenResty to 1.13.6.2
  openresty/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2153 [envdir] Updated envdir to 1.0.1
  envdir/plan.sh
  envdir/tests/test.bats
  envdir/tests/test.sh
Labels: A-core-plans, V-core-plans

#2304 [metricbeat] added metricbeat
  .bldr.toml
  metricbeat/README.md
  metricbeat/config/metricbeat.yml
  metricbeat/default.toml
  metricbeat/hooks/init
  metricbeat/hooks/run
  metricbeat/plan.sh
  metricbeat/tests/test.bats
  metricbeat/tests/test.sh
Labels: A-core-plans, V-core-plans

#2315 [Consul] Updating Consul to 1.4.2
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up

#2265 [ghc] Add ghc plan for windows
  ghc/plan.ps1
Labels: C-new-plan, I-windows

#2266 [cabal-install] Added cabal-install plan for windows
  cabal-install/plan.ps1
Labels: C-new-plan, I-windows

#2267 [shellcheck] Added shellcheck plan for windows
  shellcheck/plan.ps1
Labels: C-new-plan, I-windows

#2116 [clang] Updated clang to 7.0.1
  clang/plan.sh
  clang7/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#2132 [cpanminus] Updated cpanminus to 1.7044
  cpanminus/plan.sh
Labels: A-core-plans, V-core-plans

#2289 [msodbcsql17] Fixed file type for msodbcsql patchelf
  msodbcsql17/plan.sh
Labels: C-bug, I-linux

#2326 [dotnet-asp-core] Updating Linux plan to 2.2.2
  dotnet-asp-core/plan.sh
Labels: A-core-plans, C-minor-version-up

#2234 [elfutils] Add gcc-libs, and extra tests to confirm fix
  elfutils/plan.sh
  elfutils/tests/test.bats
Labels: A-core-plans, C-bug, V-core-plans
