Repository habitat-sh/core-plans, pull requests merged in 2019-12, with the labels that each got.

#3128 [file] fix shellcheck and add tests
  file/README.md
  file/tests/test.bats
Labels: C-base-plan

#3138 [azure-cli] Update Azure CLI to 2.0.77, update tests for new version output, standardize test file names
  azure-cli/plan.sh
  azure-cli/tests/test.bats
  azure-cli/tests/test.sh
  azure-cli/tests/tests.bats
  azure-cli/tests/tests.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#2993 [make] Add version test for make
  make/tests/test.bats
Labels: C-base-plan

#3134 [ansible] Update ansible to 2.9.1
  ansible/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3148 [cmake] Update cmake to 3.16.0
  cmake/plan.ps1
  cmake/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#2992 [tcl] Add version check test
  tcl/tests/test.bats
Labels: C-base-plan

#3117 [libarchive] Update from 3.3.3 to 3.4.0
  libarchive/plan.ps1
  libarchive/plan.sh
Labels: A-core-plans, C-base-plan, C-minor-version-up, S-needs-discussion, V-core-plans

#3120 [openssl] Update from 1.0.2r to 1.0.2t to resolve multiple CVEs
  openssl/plan.ps1
  openssl/plan.sh
Labels: A-core-plans, C-base-plan, C-minor-version-up, S-needs-discussion, T-security, V-core-plans

#3085 [go] Build windows packages
  .bldr.toml
  go/plan.ps1
Labels: C-new-plan, I-windows
