Repository habitat-sh/core-plans, pull requests merged in 2020-07, with the labels that each got.

#3400 [visual-build-tools-2017] Ensure msbuild honors environment variables above registry
  visual-build-tools-2017/plan.ps1
Labels: B-Autobuild-Building

#3404 [postgresql11] Upgraded postgresql 11 to 11.8
  postgresql11-client/plan.ps1
  postgresql11-client/plan.sh
  postgresql11/plan.sh
Labels: A-core-plans, C-minor-version-up, V-core-plans

#3074 [coredns] Added CoreDNS
  .bldr.toml
  coredns/README.md
  coredns/config/Corefile
  coredns/default.toml
  coredns/plan.sh
  coredns/tests/test.bats
  coredns/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3403 [protobuf, protobuf-cpp] Upgrade to 3.12.3
  protobuf-cpp/plan.sh
  protobuf/plan.ps1
  protobuf/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, S-needs-owner-approval, V-core-plans

#3380 [netdata] Update netdata to 1.22.1
  netdata/plan.sh
  netdata/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3429 [boringssl] Adds a test for boringssl
  boringssl/tests/test.bats
  boringssl/tests/test.sh
Labels: A-core-plans, I-linux, S-awaiting-review

#3159 [scaffolding-ruby] Added support for Rails6 apps
  scaffolding-ruby/doc/reference.md
  scaffolding-ruby/lib/scaffolding.sh
Labels: A-scaffolding, C-feature

#3438 [corretto] Update corretto to 11.0.8.10.1
  corretto/plan.ps1
  corretto/plan.sh
Labels: A-core-plans, C-minor-version-up

#3439 [opa] bump 0.21.1 -> 0.22.0
  opa/plan.sh
Labels: B-Autobuild-Building
