Repository habitat-sh/core-plans, pull requests merged in 2020-05, with the labels that each got.

#3345 [git] Update git to 2.26.2
  git/plan.ps1
  git/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3346 [gnutls] Update gnutls to 3.6.13
  gnutls/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, T-security, V-core-plans

#3347 [nginx] Update nginx to 1.18.0
  nginx/plan.ps1
  nginx/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3262 [rust] Update Rust to 1.42.0
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3371 [zookeeper] bump 3.4.14 to 3.6.1
  zookeeper/config/log4j.properties
  zookeeper/hooks/run
  zookeeper/plan.sh
  zookeeper/tests/test.bats
  zookeeper/tests/test.sh
Labels: A-core-plans, C-minor-version-up, E-easy, S-awaiting-review

#3377 [packer] Update packer to 1.5.6
  packer/plan.ps1
  packer/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3375 [openresty] Update openresty to 1.15.8.3, update tests
  openresty/plan.sh
  openresty/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans
