Repository habitat-sh/core-plans, pull requests merged in 2020-02, with the labels that each got.

#3186 [php] Update PHP to 7.4.2
  php/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3209 [nmap] Upgrading nmap to 7.80 and added tests
  nmap/plan.sh
  nmap/tests/test.bats
  nmap/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3213 [memcached] Update memcached to 1.5.22
  memcached/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3215 [yarn] Update yarn to 1.22.0
  yarn/plan.ps1
  yarn/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3218 [utf8proc] Added utf8proc
  .bldr.toml
  utf8proc/README.md
  utf8proc/plan.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3219 [subversion] Update subversion to 1.13.0, add tests
  subversion/plan.sh
  subversion/tests/test.bats
  subversion/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3216 [sudo] Update sudo to 1.8.31
  sudo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, T-security, V-core-plans

#3217 [lz4] Update lz4 to 1.9.2, add tests
  lz4/plan.sh
  lz4/tests/test.bats
  lz4/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3212 [inotify-tools] Update inotify-tools to 3.20.2.2, add tests, update upstream URL
  inotify-tools/plan.sh
  inotify-tools/tests/test.bats
  inotify-tools/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3111 [openssl11] Add new plan for OpenSSL 1.1.0
  .bldr.toml
  openssl11/README.md
  openssl11/ca-dir.patch
  openssl11/plan.sh
  openssl11/tests/test.bats
  openssl11/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#2998 [bdwgc] Update version to 8.0.4
  bdwgc/plan.sh
  bdwgc8/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3229 [ffmpeg] Update ffmpeg to 4.2.2
  ffmpeg/plan.sh
  ffmpeg4/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3235 [git] Update git to 2.25.1
  git/plan.ps1
  git/plan.sh
  git/tests/test.bats
  git/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans
