Repository habitat-sh/core-plans, pull requests merged in 2020-01, with the labels that each got.

#3166 [hugo] Update hugo to 0.61.0
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3165 [imagemagick] Update imagemagick to 7.0.9-9
  imagemagick/plan.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#3167 [iptables] Update iptables to 1.8.4
  iptables/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3172 [rust] Update Rust to 1.40.0
  rust/plan.ps1
  rust/plan.sh
Labels: A-core-plans, C-base-plan, C-minor-version-up, I-linux, I-windows, V-core-plans

#3174 [nginx] Update nginx to 1.17.7
  nginx/plan.ps1
  nginx/plan.sh
  nginx/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, T-security, V-core-plans

#3161 [ansible] Update ansible to 2.9.2
  ansible/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3180 [jenkins] Update jenkins to 2.204.1
  jenkins/plan.sh
  jenkins/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3175 [libgpg-error] Update libgpg-error to 1.36
  libgpg-error/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3176 [libgcrypt] Update libgcrypt to 1.8.5
  libgcrypt/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, T-security, V-core-plans

#3163 [envconsul] Update envconsul to 0.9.1
  envconsul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3162 [e2fsprogs] Update e2fsprogs to 1.45.4
  e2fsprogs/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3179 [libunwind] Update libunwind to 1.2.1
  libunwind/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3178 [libuv] Update libuv to 1.34.1
  libuv/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3177 [sbt] Update sbt to 1.3.7
  sbt/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3164 [gifsicle] Update gifsicle to 1.92, and modernize tests
  gifsicle/plan.sh
  gifsicle/tests/test.bats
  gifsicle/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3100 [cabal-install] Updated cabal-install to 3.0.0.0
  cabal-install/plan.ps1
  cabal-install/plan.sh
Labels: A-core-plans, C-major-version-up, I-linux, I-windows

#3146 [caddy] Update caddy to 1.0.4
  caddy/plan.sh
  caddy/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3147 [cerebro] Update cerebro to 0.8.5
  cerebro/plan.sh
  cerebro/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3184 [memcached] Update memcached to 1.5.21
  memcached/plan.sh
  memcached/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3182 [nginx] Update nginx to 1.17.8
  nginx/plan.ps1
  nginx/plan.sh
  nginx/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3185 [oniguruma] Add oniguruma
  .bldr.toml
  oniguruma/README.md
  oniguruma/default.toml
  oniguruma/plan.sh
  oniguruma/tests/test.bats
  oniguruma/tests/test.sh
Labels: A-core-plans, C-new-plan, I-linux, V-core-plans

#3183 [haproxy] Update haproxy to 2.1.2
  haproxy/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3087 [ruby] Ruby should return expected SocketError exception when DNS lookup fails
  ruby/plan.sh
  ruby/tests/test.bats
  ruby25/plan.sh
  ruby26/plan.sh
Labels: A-core-plans, I-linux, S-awaiting-review

#3194 [terraform] Upgrading to 0.12.20
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3195 Upgrading Consul to 1.6.2 and updated CI tests
  bin/ci/test_helpers.sh
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3193 [mage] Update mage to 1.9.0, update tests
  mage/plan.sh
  mage/tests/test.bats
  mage/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3191 [elixir] Update elixir to 1.10.0
  elixir/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3190 [tmux] Update tmux to 3.0a
  tmux/plan.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#3192 [hugo] Update hugo to 0.63.2
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3204 [libev] Update libev to 4.31
  libev/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3205 [go] Upgrade to 1.13.7
  go/plan.ps1
  go/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3198 [maven] Update maven to 3.6.3
  maven/plan.ps1
  maven/plan.sh
  maven/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3199 [nano] Update nano to 4.7, add tests
  nano/plan.sh
  nano/tests/test.bats
  nano/tests/test.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#3197 [node] Update node to 12.14.1
  node/plan.ps1
  node/plan.sh
  node12/plan.ps1
  node12/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3203 [strace] Update strace to 5.4
  strace/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3206 [sqlite] Update sqlite to 3.31.1, change version spec, add tests
  sqlite/plan.sh
  sqlite/tests/test.bats
  sqlite/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3202 [node8] Update node 8 to 8.17.0
  node8/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3201 [node11] Update node 11 to 11.15.0
  node11/plan.ps1
  node11/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3200 [node10] Update node10 to 10.18.1
  node10/plan.ps1
  node10/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, I-windows, V-core-plans

#3196 [Vault] Upgrading Vault to 1.3.2
  vault/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3210 [php] Make PHP testing more standard
  php/tests/libzip_support.php
  php/tests/test.bats
  php/tests/test.sh
Labels: A-core-plans, I-linux, V-core-plans
