Repository habitat-sh/core-plans, pull requests merged in 2020-09, with the labels that each got.

#3462 [icu][icu52][icu56] - Various fixes
  icu/plan.sh
  icu52/plan.sh
  icu56/plan.sh
Labels: B-Autobuild-Building, C-minor-version-up

#3469 [haproxy] Update HAProxy to 2.2.2
  haproxy/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3470 [openresty] Update OpenResty to 1.17.8.2
  openresty/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3452 [rust] Update to Rust 1.46.0
  rust/plan.ps1
  rust/plan.sh
Labels: C-minor-version-up

#3478 [Refresh2020Q3][zookeeper] Update Zookeeper to latest version
  zookeeper/plan.sh
Labels: C-minor-version-up, I-linux, R-refresh

#3475 [Refresh2020Q3][htop] - Major version change & source change
  htop/plan.sh
Labels: C-major-version-up, R-refresh
