Repository habitat-sh/core-plans, pull requests merged in 2020-06, with the labels that each got.

#3379 [graphviz] Update graphviz to 2.44.0
  graphviz/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3378 [consul] Update consul to 1.7.3
  consul/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3376 [terraform] Update terraform to 0.12.26
  terraform/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3168 Update ipvsadm to 1.30, modernize tests, fix ipvsadm-save with coreut…
  ipvsadm/plan.sh
  ipvsadm/tests/test.bats
  ipvsadm/tests/test.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3384 [grafana] Update grafana to 7.0.1
  grafana/plan.sh
Labels: A-core-plans, C-major-version-up, I-linux, V-core-plans

#3387 [sbt] Update sbt to 1.3.12
  sbt/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3385 [strace] Update strace to 5.7
  strace/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, V-core-plans

#3393 [dsc-core] fix concurrency issues
  dsc-core/DSCCore.psm1
  dsc-core/README.md
  dsc-core/plan.ps1
  dsc-core/tests/test.pester.ps1
Labels: I-windows

#3386 [hugo] Update hugo to 0.72.0
  hugo/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, S-needs-owner-approval, V-core-plans

#3391 [filebeat] Update filebeat to 7.7.1
  filebeat/plan.sh
Labels: A-core-plans, C-minor-version-up, I-linux, S-needs-owner-approval, V-core-plans

#3392 [ps-lock] use -IsPath when setting PSModulePath so it works in a local studio
  .bldr.toml
  ps-lock/README.md
  ps-lock/plan.ps1
Labels: I-windows
